Repository trustbloc/wallet, pull requests merged in 2020-12, with the labels that each got.

#553 chore: udpate agent-sdk with latest change
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  go.mod
  go.sum
  test/bdd/go.sum
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#558 fix: Remove alert message while registering device
  cmd/wallet-web/src/pages/chapi/RegisterDevice.vue
  cmd/wallet-web/src/pages/chapi/wallet/device/register.js
Labels: cla-signed

#559 chore: enable hub-kms to hub-auth integration
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#562 feat: Connections will not be store in local storage
  cmd/wallet-web/src/pages/chapi/wallet/get/didConn.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/wallet-web/src/pages/chapi/wallet/register/walletManager.js
Labels: cla-signed

#564 chore: Update agent-sdk and hub-kms dependency
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/bdd/fixtures/wallet-web/.env
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#565 chore: update with latest aries-frmework-go and agent-sdk
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  go.mod
  go.sum
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#566 feat: Enable WebKMS
  cmd/wallet-web/src/store/modules/options.js
  images/wallet-web/Dockerfile
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#568 chore: update bdd test go.sum with latest aries-framework-go
  test/bdd/go.sum
Labels: cla-signed

#569 docs: Add ops kms url to localhosts
  docs/test/test.md
Labels: cla-signed

#570 fix: Addressing console warnings.
  cmd/wallet-web/src/components/SidebarPlugin/index.js
  cmd/wallet-web/src/pages/Dashboard.vue
Labels: cla-signed

#571 feat: Update EDV server version (which now supports batch requests)
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#572 feat: use edv batch write
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/store/modules/options.js
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#563 refactor: bearer token usage for hub-kms/oathkeeper
  pkg/restapi/oidc/operations.go
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/bdd/fixtures/wallet-web/oathkeeper-config/auth-keyserver/config.yaml
  test/bdd/fixtures/wallet-web/oathkeeper-config/auth-keyserver/rules/resource-server.json
  test/bdd/fixtures/wallet-web/oathkeeper-config/ops-keyserver/config.yaml
  test/bdd/fixtures/wallet-web/oathkeeper-config/ops-keyserver/rules/resource-server.json
Labels: cla-signed, refactor

#573 fix: add EDV_BATCH_LIMIT to bdd test
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#575 chore: disable edv caching and batching
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#576 feat: Removes indexdb usage
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/pages/chapi/wallet/common/keyValStore.js
  cmd/wallet-web/src/pages/chapi/wallet/didmgmt/didManager.js
  cmd/wallet-web/src/pages/chapi/wallet/get/didConn.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/wallet-web/src/pages/chapi/wallet/register/register.js
  cmd/wallet-web/src/pages/chapi/wallet/register/walletManager.js
  cmd/wallet-web/src/store/modules/user.js
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#577 fix: demo login
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/bdd/fixtures/wallet-web/oathkeeper-config/bdd-auth-keyserver/config.yaml
  test/bdd/fixtures/wallet-web/oathkeeper-config/bdd-auth-keyserver/rules/resource-server.json
  test/bdd/fixtures/wallet-web/oathkeeper-config/bdd-ops-keyserver/config.yaml
  test/bdd/fixtures/wallet-web/oathkeeper-config/bdd-ops-keyserver/rules/resource-server.json
  test/bdd/fixtures/wallet-web/oathkeeper-config/demo-auth-keyserver/config.yaml
  test/bdd/fixtures/wallet-web/oathkeeper-config/demo-auth-keyserver/rules/resource-server.json
  test/bdd/fixtures/wallet-web/oathkeeper-config/demo-ops-keyserver/config.yaml
  test/bdd/fixtures/wallet-web/oathkeeper-config/demo-ops-keyserver/rules/resource-server.json
Labels: bug, cla-signed

#579 fix: Update wallet with hub-kms image
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/options.js
  pkg/restapi/oidc/operations.go
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/bdd/fixtures/wallet-web/oathkeeper-config/bdd-auth-keyserver/rules/resource-server.json
  test/bdd/fixtures/wallet-web/oathkeeper-config/bdd-ops-keyserver/rules/resource-server.json
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#581 fix: DIDAuth store error
  cmd/wallet-web/src/pages/chapi/wallet/get/didAuth.js
Labels: cla-signed

#578 fix: use KMS capability for OPS keyserver operations
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/options.js
  docs/test/test.md
  go.mod
  go.sum
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  pkg/restapi/oidc/webkms.go
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/bdd/fixtures/wallet-web/oathkeeper-config/demo-auth-keyserver/config.yaml
  test/bdd/fixtures/wallet-web/oathkeeper-config/demo-ops-keyserver/config.yaml
  test/bdd/go.sum
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: blocked, bug, cla-signed, test

#586 chore: update did-method, sidetree-mock, agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/bdd/fixtures/wallet-web/.env
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#584 feat: Update EDV server version
  test/bdd/fixtures/wallet-web/.env
Labels: cla-signed

#588 fix: Stores DID id (metadata)
  cmd/wallet-web/src/pages/DIDManagement.vue
Labels: cla-signed

#582 feat: add edv batch write
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/pages/chapi/wallet/common/keyValStore.js
  cmd/wallet-web/src/pages/chapi/wallet/get/didConn.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentials.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/wallet-web/src/pages/chapi/wallet/store/saveCredential.js
  cmd/wallet-web/src/store/modules/options.js
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#590 chore: bump test coverage
  pkg/restapi/oidc/operations_test.go
  pkg/restapi/oidc/webkms_test.go
Labels: chore, cla-signed

#591 chore: update agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/options.js
  go.mod
  go.sum
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#589 fix: replace DID with Digital Identity
  cmd/wallet-web/src/pages/DIDManagement.vue
  cmd/wallet-web/src/pages/Layout/DashboardLayout.vue
Labels: cla-signed

#592 fix: Skip user registration for onboarded user
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/pages/chapi/wallet/common/keyValStore.js
  cmd/wallet-web/src/pages/chapi/wallet/register/register.js
Labels: cla-signed

#593 feat: Update EDV server version
  test/bdd/fixtures/wallet-web/.env
Labels: cla-signed

#594 feat: Update agent-sdk version
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#595 chore: update agent-sdk
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/options.js
  go.mod
  go.sum
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  test/wallet-web/package.json
Labels: cla-signed

#596 chore: upgrade to the latest hub-kms
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#598 feat: Update EDV server version
  test/bdd/fixtures/wallet-web/.env
Labels: cla-signed

#599 chore: update agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#597 fix: Login UX change and alert fixes.
  cmd/wallet-server/go.sum
  cmd/wallet-web/package.json
  cmd/wallet-web/src/assets/img/sidebar-2.jpg
  cmd/wallet-web/src/assets/img/topbar-2.jpg
  cmd/wallet-web/src/assets/img/wallet.jpg
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/pages/chapi/RegisterDevice.vue
  cmd/wallet-web/src/pages/chapi/wallet/device/login.js
  test/bdd/fixtures/wallet-web/.env
  test/bdd/go.sum
  test/bdd/mock/demo-login-consent-server/templates/consent.html
Labels: cla-signed

#602 chore: update dependencies
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/pages/chapi/wallet/register/register.js
  test/bdd/fixtures/wallet-web/.env
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#603 fix: UI alignment fix
  cmd/wallet-web/src/pages/chapi/Login.vue
Labels: cla-signed

#604 chore: Release 0.1.5
  .npmrc
  ci/azure-pipelines.yml
  ci/version_var.sh
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/.npmrc
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  go.mod
  go.sum
  test/bdd/fixtures/wallet-web/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/wallet-web/.npmrc
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#605 chore: Complete Release 0.1.5
  ci/version_var.sh
Labels: cla-signed

#606 fix: Chapi UI Button alignment
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/store/modules/options.js
Labels: cla-signed

#607 feat: Allows using wallet-web-dev-start target for local development
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/options.js
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/bdd/fixtures/wallet-web/hydra-config/demo_auth-rest-hydra_configure.sh
  test/bdd/fixtures/wallet-web/oathkeeper-config/demo-auth-keyserver/config.yaml
  test/bdd/fixtures/wallet-web/oathkeeper-config/demo-ops-keyserver/config.yaml
Labels: cla-signed

#609 fix: security vulnerability
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#612 feat: wallet didconnect - wait for state complete message
  cmd/wallet-web/src/pages/chapi/wallet/common/didExchange.js
  cmd/wallet-web/src/pages/chapi/wallet/didcomm/blindedRouter.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  test/wallet-web/test/mocks/adapters/issuerAdapter.js
Labels: cla-signed

#613 chore: Log wallet connect execute time
  cmd/wallet-web/src/pages/chapi/wallet/get/didConn.js
  cmd/wallet-web/src/pages/chapi/wallet/register/register.js
Labels: cla-signed

#610 fix: DID table updates automatically and loading screen
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/DIDManagement.vue
  cmd/wallet-web/src/pages/chapi/Login.vue
Labels: cla-signed

#615 chore: update agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#616 feat: mediator connect performance enhancement
  cmd/wallet-web/src/pages/chapi/wallet/register/register.js
Labels: cla-signed

#618 feat: wallet register to run in background after login
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/pages/chapi/wallet/register/register.js
Labels: cla-signed

#622 feat: vuex state to track background user registration
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/pages/chapi/wallet/register/register.js
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed

#620 fix: Replace mem with persistant store in wallet-server start up
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-server/startcmd/start.go
  cmd/wallet-server/startcmd/start_test.go
  pkg/restapi/common/store/helper.go
  pkg/restapi/common/store/tokens/store.go
  pkg/restapi/common/store/user/store.go
  pkg/restapi/device/operations.go
  pkg/restapi/device/operations_test.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/bdd/fixtures/wallet-web/mysql-config/mysql_config.sql
Labels: cla-signed

#623 chore: migrate wallet to agent sdk messenger command
  cmd/wallet-web/src/pages/chapi/wallet/common/messaging.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/wallet-web/src/pages/chapi/wallet/index.js
  cmd/wallet-web/src/store/modules/user.js
  test/wallet-web/test/common.js
Labels: cla-signed

#625 feat: wallet blinded routing to use agent-sdk commands
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/chapi/wallet/didcomm/blindedRouter.js
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed
