Repository trustbloc/wallet, pull requests merged in 2020-11, with the labels that each got.

#459 chore: update edge-sdk revision
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
Labels: cla-signed

#460 chore: enable RP blinded routing
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  test/user-agent/test/common.js
Labels: cla-signed

#462 docs: webwallet docs for all supported features
  Makefile
  README.md
  docs/components/web_wallet.md
  docs/dev/dev-mode.md
  scripts/user_agent_dev_start.sh
Labels: cla-signed

#464 fix: Broken dev mode link
  README.md
Labels: cla-signed

#466 chore: update agent-sdk
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
  cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
  test/bdd/fixtures/agent-wasm/.env
  test/user-agent/package-lock.json
  test/user-agent/package.json
Labels: cla-signed

#467 chore: update agent-sdk revision
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
Labels: cla-signed

#469 chore: hub-router dependency update
  test/bdd/fixtures/agent-wasm/.env
Labels: cla-signed

#470 feat: http-server healthcheck endpoint
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  test/bdd/bdd_test.go
  test/bdd/features/healthcheck.feature
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/healthcheck/steps.go
  test/user-agent/package-lock.json
Labels: cla-signed, enhancement

#472 chore: update aries-framework-go and did-method revision
  cmd/user-agent/package.json
  test/bdd/fixtures/agent-wasm/.env
Labels: cla-signed

#473 chore: update aries revision
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
Labels: cla-signed

#474 fix: agent-sdk missing storage type
  cmd/http-server/startcmd/start.go
  cmd/user-agent/src/store/modules/options.js
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#477 chore: update sidetree-mock and did-method
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
  cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
  test/bdd/fixtures/agent-wasm/.env
  test/user-agent/package-lock.json
  test/user-agent/package.json
  test/user-agent/test/common.js
Labels: cla-signed

#479 chore: Hub-router docker update
  test/bdd/fixtures/agent-wasm/.env
Labels: cla-signed

#480 refactor: #471 login via OIDC
  Makefile
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  cmd/user-agent/src/pages/chapi/Login.vue
  cmd/user-agent/src/store/modules/user.js
  docs/test/test.md
  pkg/restapi/common/common.go
  pkg/restapi/common/common_test.go
  pkg/restapi/common/oidc/api.go
  pkg/restapi/common/oidc/client.go
  pkg/restapi/common/oidc/client_test.go
  pkg/restapi/common/oidc/mock.go
  pkg/restapi/common/oidc/mock_test.go
  pkg/restapi/common/store/tokens/store.go
  pkg/restapi/common/store/user/store.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  scripts/generate_test_keys.sh
  test/bdd/features/healthcheck.feature
  test/bdd/features/login.feature
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/docker-compose.yml
  test/bdd/fixtures/agent-wasm/hydra-config/bddtest_hydra_configure.sh
  test/bdd/fixtures/agent-wasm/hydra-config/demo_hydra_configure.sh
  test/bdd/fixtures/agent-wasm/mysql-config/mysql_config.sql
  test/bdd/mock/bddtest-login-consent-server/go.mod
  test/bdd/mock/bddtest-login-consent-server/go.sum
  test/bdd/mock/bddtest-login-consent-server/image/Dockerfile
  test/bdd/mock/bddtest-login-consent-server/main.go
  test/bdd/mock/bddtest-login-consent-server/server.go
  test/bdd/mock/demo-login-consent-server/go.mod
  test/bdd/mock/demo-login-consent-server/go.sum
  test/bdd/mock/demo-login-consent-server/image/Dockerfile
  test/bdd/mock/demo-login-consent-server/main.go
  test/bdd/mock/demo-login-consent-server/main_test.go
  test/bdd/mock/demo-login-consent-server/templates/bankconsent.html
  test/bdd/mock/demo-login-consent-server/templates/banklogin.html
  test/bdd/mock/demo-login-consent-server/templates/consent.html
  test/bdd/mock/demo-login-consent-server/templates/img/consent.png
  test/bdd/mock/demo-login-consent-server/templates/img/logo.png
  test/bdd/mock/demo-login-consent-server/templates/login.html
  test/bdd/mock/demo-login-consent-server/templates/uploadCred.html
  test/bdd/mock/demo-login-consent-server/templates/uploadCredConsent.html
  test/bdd/pkg/login/steps.go
  test/user-agent/package-lock.json
Labels: cla-signed, refactor

#481 chore: update trustbloc-did-method revision
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/config-data/stakeholder.one_8088.json
  test/bdd/fixtures/agent-wasm/config-data/testnet.trustbloc.local.json
  test/user-agent/package-lock.json
  test/user-agent/package.json
Labels: cla-signed

#482 feat: Hook Device REST handlers into http-server
  cmd/http-server/go.mod
  cmd/http-server/go.sum
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  pkg/restapi/device/operations.go
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#486 chore: Update edge-core lib dependency
  cmd/http-server/go.mod
  cmd/http-server/go.sum
  go.mod
  go.sum
  test/bdd/go.mod
  test/bdd/go.sum
Labels: cla-signed

#490 feat: AuthZ Hub-KMS basic integration
  cmd/http-server/go.sum
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  go.sum
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#491 chore: update edv docker image version
  test/bdd/fixtures/agent-wasm/.env
Labels: cla-signed

#495 feat: Integrate Operational key server and Key SDS server
  cmd/http-server/go.mod
  cmd/http-server/go.sum
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  go.mod
  go.sum
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/couchdb-config/config.ini
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#494 feat: Device Registration vue change
  cmd/http-server/startcmd/start.go
  cmd/user-agent/src/pages/Layout/TopNavbar.vue
  cmd/user-agent/src/pages/chapi/RegisterDevice.vue
  cmd/user-agent/src/pages/chapi/wallet/device/register.js
  cmd/user-agent/src/pages/chapi/wallet/index.js
  pkg/restapi/device/operations.go
  pkg/restapi/device/operations_test.go
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#498 fix: Check the user's session cookie before redirecting to the OIDC
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
Labels: cla-signed

#499 feat: Create User SDS Vault during onboarding
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#492 refactor: Separates UI against the backend
  .gitignore
  Makefile
  ci/azure-pipelines.yml
  ci/version_var.sh
  cmd/user-agent-support/go.mod
  cmd/user-agent-support/go.sum
  cmd/user-agent-support/main.go
  cmd/user-agent-support/main_test.go
  cmd/user-agent-support/startcmd/start.go
  cmd/user-agent-support/startcmd/start_test.go
  cmd/user-agent/src/pages/Layout/DashboardLayout.vue
  cmd/user-agent/src/pages/chapi/Login.vue
  cmd/user-agent/src/pages/chapi/wallet/device/register.js
  cmd/user-agent/src/store/modules/options.js
  cmd/user-agent/src/store/modules/user.js
  cmd/user-agent/vue.config.js
  docs/components/web_wallet.md
  docs/dev/dev-mode.md
  docs/test/test.md
  images/user-agent-support/Dockerfile
  images/user-agent/Dockerfile
  images/user-agent/templates/default.conf.template
  pkg/restapi/device/operations.go
  pkg/restapi/oidc/operations_test.go
  scripts/build_agent_wasm.sh
  scripts/check_js_integration.sh
  scripts/check_lint.sh
  scripts/check_unit.sh
  scripts/check_user_agent_support_integration.sh
  scripts/generate_test_config.sh
  scripts/generate_test_keys.sh
  scripts/user_agent_dev_start.sh
  scripts/user_agent_start.sh
  test/bdd/bdd_test.go
  test/bdd/fixtures/agent-wasm/config/stakeholder.one:8088.json
  test/bdd/fixtures/agent-wasm/config/testnet.trustbloc.local.json
  test/bdd/fixtures/user-agent/.env
  test/bdd/fixtures/user-agent/config-data/stakeholder.one_8088.json
  test/bdd/fixtures/user-agent/config-data/testnet.trustbloc.local.json
  test/bdd/fixtures/user-agent/config.json
  test/bdd/fixtures/user-agent/couchdb-config/config.ini
  test/bdd/fixtures/user-agent/docker-compose.yml
  test/bdd/fixtures/user-agent/hydra-config/bddtest_hydra_configure.sh
  test/bdd/fixtures/user-agent/hydra-config/demo_hydra_configure.sh
  test/bdd/fixtures/user-agent/mysql-config/mysql_config.sql
  test/bdd/fixtures/user-agent/run-uni-resolver-web.sh
  test/bdd/pkg/login/steps.go
Labels: cla-signed

#501 refactor: Rename SDS to EDV and remove legacy EDV storage code
  cmd/user-agent-support/startcmd/start.go
  cmd/user-agent-support/startcmd/start_test.go
  cmd/user-agent/src/pages/TablePresentation.vue
  cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
  cmd/user-agent/src/pages/chapi/wallet/register/walletManager.js
  cmd/user-agent/src/pages/chapi/wallet/store/saveCredential.js
  cmd/user-agent/src/store/modules/options.js
  docs/test/test.md
  images/user-agent/Dockerfile
  images/user-agent/templates/default.conf.template
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/fixtures/user-agent/.env
  test/bdd/fixtures/user-agent/docker-compose.yml
  test/user-agent/test/common.js
Labels: cla-signed

#503 fix: Fixes nginx configuration
  images/user-agent/templates/default.conf.template
  test/bdd/fixtures/agent-wasm/config/stakeholder.one:8088.json
  test/bdd/fixtures/agent-wasm/config/testnet.trustbloc.local.json
  test/bdd/fixtures/user-agent/docker-compose.yml
Labels: cla-signed

#504 fix: Update ops-kms store type and edv port variable
  images/user-agent/templates/default.conf.template
  test/bdd/fixtures/user-agent/.env
  test/bdd/fixtures/user-agent/docker-compose.yml
Labels: cla-signed

#505 chore: unblock #506 by temporarily storing bootstrap data locally
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/user-agent/package-lock.json
Labels: chore, cla-signed

#508 feat: EDV storage
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
  cmd/user-agent/src/store/modules/options.js
  images/user-agent/Dockerfile
  test/bdd/fixtures/user-agent/docker-compose.yml
  test/user-agent/package-lock.json
  test/user-agent/package.json
Labels: cla-signed

#509 feat: Default storage type to IndexedDB
  cmd/user-agent/src/store/modules/options.js
  images/user-agent/Dockerfile
  test/bdd/fixtures/user-agent/docker-compose.yml
Labels: cla-signed

#511 fix: Updated EDV server docker image
  images/user-agent/Dockerfile
  test/bdd/fixtures/user-agent/.env
  test/bdd/fixtures/user-agent/docker-compose.yml
Labels: cla-signed

#515 feat: Update half secret in hub-auth
  cmd/wallet-server/startcmd/start.go
  cmd/wallet-server/startcmd/start_test.go
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#516 chore: Create Controller for ops kms and key sds
  .gitignore
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  go.mod
  go.sum
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  scripts/generate_test_keys.sh
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#517 chore: update hub-kms revision
  Makefile
  docs/test/test.md
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#520 feat: Update EDV to use zcap
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  go.mod
  go.sum
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  pkg/restapi/oidc/signer.go
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#519 feat: EDV vault ID storage workaround
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed

#522 fix: Fixes cookie usage in iframe
  docs/components/web_wallet.md
  docs/test/test.md
  pkg/restapi/common/store/cookie/store.go
  scripts/generate_test_keys.sh
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/bdd/fixtures/wallet-web/hydra-config/demo_auth-rest-hydra_configure.sh
Labels: cla-signed

#523 feat: Post user bootstrap data to hub-auth
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/fixtures/wallet-web/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/pkg/login/steps.go
Labels: cla-signed

#525 fix: Fixes cookie path
  pkg/restapi/common/store/cookie/store.go
Labels: cla-signed

#524 fix: Remove EDV Vault ID storage workaround
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed

#527 feat: migration to agent-sdk commands
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/chapi/wallet/didcomm/blindedRouter.js
  cmd/wallet-web/src/pages/chapi/wallet/didcomm/mediator.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/wallet-web/src/pages/chapi/wallet/index.js
  cmd/wallet-web/src/pages/chapi/wallet/register/register.js
  cmd/wallet-web/src/store/modules/user.js
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
  test/wallet-web/test/common.js
  test/wallet-web/test/mocks/adapters/issuerAdapter.js
  test/wallet-web/test/wallet/walletCredentialQuery.blinded.spec.js
  test/wallet-web/test/wallet/walletCredentialQuery.spec.js
Labels: cla-signed

#528 feat: Login device with touch ID implementation
  cmd/wallet-server/startcmd/start.go
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/pages/chapi/wallet/device/login.js
  cmd/wallet-web/src/pages/chapi/wallet/index.js
  pkg/restapi/device/operations.go
  pkg/restapi/device/operations_test.go
Labels: cla-signed

#530 chore: update agent-sdk revision
  Makefile
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/options.js
  go.mod
  go.sum
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#532 feat: Update agent-sdk version
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/events/index.js
  cmd/wallet-web/src/pages/chapi/wallet/common/messaging.js
  test/wallet-web/package.json
Labels: cla-signed

#533 chore: Update agent-sdk version
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#534 feat: enable edv zcap
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#535 chore: update agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  docs/test/test.md
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#536 fix: Increase timeout to accommodate slow EDV server
  cmd/wallet-web/src/pages/chapi/wallet/didcomm/blindedRouter.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
Labels: cla-signed

#537 fix: Increase get credential retries to accommodate slow EDV server
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
Labels: cla-signed

#538 chore: update edv and hub-kms revision
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  go.mod
  go.sum
  test/bdd/fixtures/wallet-web/.env
Labels: cla-signed

#539 feat: Pass half secret share to hub-kms
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/options.js
  pkg/restapi/common/store/user/store.go
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  pkg/restapi/oidc/signer.go
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#542 chore: update hub-kms image
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/bdd/go.mod
  test/bdd/go.sum
Labels: chore, cla-signed

#545 chore: add edv cache
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/options.js
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  test/bdd/fixtures/wallet-web/docker-compose.yml
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#548 chore: Updates agent-sdk version
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#550 feat: Add oathkeeper for edv
  ci/azure-pipelines.yml
  docs/test/test.md
  go.mod
  go.sum
  pkg/restapi/oidc/operations.go
  scripts/generate_test_keys.sh
  test/bdd/fixtures/bdd-edv-oathkeeper/config.yaml
  test/bdd/fixtures/bdd-edv-oathkeeper/rules/resource-server.json
  test/bdd/fixtures/edv-oathkeeper/config.yaml
  test/bdd/fixtures/edv-oathkeeper/rules/resource-server.json
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#551 feat: Wallet onboard - create edvOps and edvHMAC keys
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/pkg/login/steps.go
Labels: cla-signed

#554 chore: Update EDV server version
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose.yml
Labels: cla-signed

#555 chore: Updates agent-sdk revision
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  go.mod
  go.sum
  test/bdd/go.sum
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#556 feat: Support to configure KMS
  cmd/wallet-web/src/store/modules/options.js
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
Labels: cla-signed
