Repository trustbloc/wallet, pull requests merged in 2020-09, with the labels that each got.

#325 chore: complete release v0.1.4
  ci/version_var.sh
Labels: cla-signed

#331 feat: access control for wallet dashboard & vuex based login
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/Dashboard.vue
  cmd/user-agent/src/pages/chapi/Login.vue
  cmd/user-agent/src/pages/chapi/Logout.vue
  cmd/user-agent/src/pages/chapi/wallet/register/walletManager.js
  cmd/user-agent/src/router/index.js
  cmd/user-agent/src/store/index.js
  cmd/user-agent/src/store/modules/user.js
Labels: cla-signed

#326 feat: Use username from login for SDS vault creation
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  cmd/trustbloc-agent-js-worker/main.go
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
  cmd/user-agent/src/pages/chapi/wallet/register/register.js
  cmd/user-agent/src/pages/chapi/wallet/store/saveCredential.js
  pkg/controller/command/credentialclient/command.go
  pkg/controller/command/credentialclient/command_test.go
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
  pkg/controller/command/presentationclient/command.go
  pkg/controller/command/presentationclient/command_test.go
  pkg/controller/command/sdscomm/models.go
  pkg/controller/command/sdscomm/sdscomm.go
  pkg/controller/command/sdscomm/sdscomm_test.go
  pkg/controller/controller.go
  test/user-agent/test/common.js
Labels: cla-signed

#335 fix: add retry for router register
  cmd/user-agent/src/pages/chapi/wallet/didcomm/connections.js
Labels: cla-signed

#338 feat: user vuex state for webwallet
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/DIDManagement.vue
  cmd/user-agent/src/pages/Dashboard.vue
  cmd/user-agent/src/pages/TablePresentation.vue
  cmd/user-agent/src/pages/chapi/DIDConnect.vue
  cmd/user-agent/src/pages/chapi/Login.vue
  cmd/user-agent/src/pages/chapi/Logout.vue
  cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
  cmd/user-agent/src/pages/chapi/Store.vue
  cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
  cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/user-agent/src/pages/chapi/wallet/register/register.js
  cmd/user-agent/src/pages/chapi/wallet/register/walletManager.js
  cmd/user-agent/src/pages/chapi/wallet/store/saveCredential.js
  cmd/user-agent/src/store/modules/user.js
  test/user-agent/package-lock.json
  test/user-agent/package.json
  test/user-agent/test/common.js
  test/user-agent/test/wallet/walletCredentialQuery.spec.js
  test/user-agent/test/wallet/walletStore.spec.js
Labels: cla-signed

#341 chore: update sidetree, did-method
  cmd/trustbloc-agent-js-worker/go.sum
  go.mod
  go.sum
  test/bdd/fixtures/agent-wasm/.env
Labels: cla-signed

#344 feat: block access to CHAPI iframe for invalid session
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/Layout/TopNavbar.vue
  cmd/user-agent/src/pages/chapi/BlockNoAuth.vue
  cmd/user-agent/src/pages/chapi/DIDConnect.vue
  cmd/user-agent/src/pages/chapi/Login.vue
  cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
  cmd/user-agent/src/pages/chapi/wallet/register/register.js
  cmd/user-agent/src/router/index.js
Labels: cla-signed

#347 feat: webwallet - aries per user login
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/DIDManagement.vue
  cmd/user-agent/src/pages/Dashboard.vue
  cmd/user-agent/src/pages/chapi/DIDAuth.vue
  cmd/user-agent/src/pages/chapi/DIDConnect.vue
  cmd/user-agent/src/pages/chapi/GetCredentials.vue
  cmd/user-agent/src/pages/chapi/Login.vue
  cmd/user-agent/src/pages/chapi/Logout.vue
  cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
  cmd/user-agent/src/pages/chapi/Store.vue
  cmd/user-agent/src/store/modules/user.js
  test/user-agent/test/common.js
  test/user-agent/test/wallet/walletCredentialQuery.spec.js
  test/user-agent/test/wallet/walletStore.spec.js
Labels: cla-signed

#349 chore: refactor user agent wallet left navigation
  cmd/user-agent/src/pages/Layout/DashboardLayout.vue
  cmd/user-agent/src/pages/Layout/TopNavbar.vue
  cmd/user-agent/src/pages/TablePresentation.vue
  cmd/user-agent/src/pages/chapi/Login.vue
  cmd/user-agent/src/router/index.js
Labels: cla-signed

#351 feat: user agent wallet demos to reuse webwallet user aries
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/Connections.vue
  cmd/user-agent/src/pages/DIDManagement.vue
  cmd/user-agent/src/pages/Dashboard.vue
  cmd/user-agent/src/pages/IssueCredential.vue
  cmd/user-agent/src/pages/PresentProof.vue
  cmd/user-agent/src/pages/TablePresentation.vue
  cmd/user-agent/src/pages/WebWallet.vue
  cmd/user-agent/src/pages/chapi/DIDAuth.vue
  cmd/user-agent/src/pages/chapi/DIDConnect.vue
  cmd/user-agent/src/pages/chapi/GetCredentials.vue
  cmd/user-agent/src/pages/chapi/Logout.vue
  cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
  cmd/user-agent/src/pages/chapi/Store.vue
  cmd/user-agent/src/router/index.js
  cmd/user-agent/src/store/modules/connections.js
  cmd/user-agent/src/store/modules/credentials.js
  cmd/user-agent/src/store/modules/init.js
  cmd/user-agent/src/store/modules/mediator.js
  cmd/user-agent/src/store/modules/presentation.js
  cmd/user-agent/src/store/modules/user.js
Labels: cla-signed

#355 feat: user agent configuration load using vuex
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/DIDManagement.vue
  cmd/user-agent/src/pages/Relationships.vue
  cmd/user-agent/src/pages/TablePresentation.vue
  cmd/user-agent/src/pages/WebWallet.vue
  cmd/user-agent/src/pages/chapi/DIDConnect.vue
  cmd/user-agent/src/pages/chapi/Login.vue
  cmd/user-agent/src/pages/chapi/Logout.vue
  cmd/user-agent/src/pages/chapi/Store.vue
  cmd/user-agent/src/pages/chapi/Worker.vue
  cmd/user-agent/src/store/index.js
  cmd/user-agent/src/store/modules/init.js
  cmd/user-agent/src/store/modules/options.js
  cmd/user-agent/src/store/modules/user.js
  test/user-agent/test/common.js
  test/user-agent/test/wallet/walletCredentialQuery.spec.js
  test/user-agent/test/wallet/walletStore.spec.js
Labels: cla-signed

#356 chore: update to latest trustbloc-did-method
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#365 feat: updated UI for wallet dashboard
  cmd/user-agent/src/assets/img/sidebar-2.jpg
  cmd/user-agent/src/assets/img/topbar-2.jpg
  cmd/user-agent/src/assets/scss/md/_sidebar-and-main-panel.scss
  cmd/user-agent/src/components/SidebarPlugin/SideBar.vue
  cmd/user-agent/src/components/Tables/SimpleTable.vue
  cmd/user-agent/src/pages/Dashboard.vue
  cmd/user-agent/src/pages/Layout/TopNavbar.vue
  cmd/user-agent/src/router/index.js
  cmd/user-agent/src/store/modules/user.js
Labels: cla-signed

#367 feat: blinded routing configuration
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  cmd/user-agent/src/pages/Dashboard.vue
  cmd/user-agent/src/store/modules/options.js
Labels: cla-signed

#359 chore: upgrade to Go 1.15
  .golangci.yml
  Makefile
  ci/azure-pipelines.yml
  cmd/http-server/go.mod
  cmd/http-server/go.sum
  cmd/http-server/main.go
  cmd/http-server/main_test.go
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  cmd/trustbloc-agent-js-worker/go.mod
  docs/test/test.md
  go.mod
  scripts/check_lint.sh
Labels: chore, cla-signed

#360 fix: #173 remove dependency on $GITHUB_TOKEN
  Makefile
  ci/azure-pipelines.yml
  cmd/user-agent/.npmrc
  docs/test/test.md
  images/agent-wasm/Dockerfile
  scripts/check_js_integration.sh
  scripts/check_lint.sh
  test/user-agent/.npmrc
Labels: bug, cla-signed

#370 fix: #369 missing npm registry config
  cmd/user-agent/.npmrc
  test/user-agent/.npmrc
Labels: bug, cla-signed

#358 feat: #357 http-server OIDC /login endpoint
  cmd/http-server/go.mod
  cmd/http-server/go.sum
  go.mod
  go.sum
  pkg/restapi/common/common.go
  pkg/restapi/common/common_test.go
  pkg/restapi/common/httphandler.go
  pkg/restapi/common/httphandler_test.go
  pkg/restapi/oidc/dependencies.go
  pkg/restapi/oidc/helper.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  pkg/restapi/oidc/transientData.go
Labels: cla-signed, enhancement

#371 fix: security vulnerabilities in JS code
  cmd/trustbloc-agent-js-worker/package-lock.json
  cmd/trustbloc-agent-js-worker/package.json
  test/bdd/fixtures/agent-wasm/package-lock.json
Labels: cla-signed

#368 feat: #361 hook OIDC REST handlers into http-server
  cmd/http-server/go.mod
  cmd/http-server/go.sum
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  cmd/user-agent/package.json
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/Layout/DashboardLayout.vue
  cmd/user-agent/src/pages/chapi/Login.vue
  cmd/user-agent/src/pages/chapi/Worker.vue
  cmd/user-agent/src/pages/chapi/wallet/register/register.js
  cmd/user-agent/src/router/index.js
  cmd/user-agent/src/store/modules/options.js
  cmd/user-agent/vue.config.js
  docs/components/web_wallet.md
  docs/test/test.md
  pkg/restapi/oidc/dependencies.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/fixtures/agent-wasm/docker-compose.yml
  test/bdd/fixtures/agent-wasm/oidc-config/clients-config.json
Labels: cla-signed, enhancement

#383 feat: Router - replace aries-agent with hub-router
  cmd/user-agent/src/pages/chapi/wallet/didcomm/connections.js
  cmd/user-agent/src/store/modules/mediator.js
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#378 feat: #375 OIDC callback endpoint
  cmd/http-server/startcmd/start.go
  pkg/restapi/common/oidc/client.go
  pkg/restapi/common/oidc/client_test.go
  pkg/restapi/oidc/dependencies.go
  pkg/restapi/oidc/helper.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  pkg/restapi/oidc/persistedData.go
Labels: cla-signed, enhancement
