Repository trustbloc/wallet, pull requests merged in 2020-10, with the labels that each got.

#387 feat: #379 session cookies
  cmd/http-server/go.sum
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  cmd/trustbloc-agent-js-worker/go.sum
  go.mod
  go.sum
  pkg/restapi/common/common.go
  pkg/restapi/oidc/dependencies.go
  pkg/restapi/oidc/helper.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  scripts/generate_test_keys.sh
  test/bdd/fixtures/.gitignore
  test/bdd/fixtures/agent-wasm/docker-compose.yml
  test/user-agent/package-lock.json
Labels: cla-signed, enhancement

#389 fix: #381 overwriting existing user records on every login
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  pkg/restapi/oidc/persistedData.go
Labels: bug, cla-signed

#399 fix: cors and vue-cli-service serve issue fixes
  cmd/http-server/startcmd/start.go
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/chapi/BlockNoAuth.vue
  cmd/user-agent/src/pages/chapi/Worker.vue
  cmd/user-agent/src/pages/chapi/wallet/register/register.js
  cmd/user-agent/vue.config.js
Labels: cla-signed

#402 refactor: #400 http-server store packages
  cmd/http-server/go.mod
  cmd/http-server/go.sum
  pkg/restapi/common/oidc/api.go
  pkg/restapi/common/oidc/client.go
  pkg/restapi/common/oidc/mock.go
  pkg/restapi/common/oidc/mock_test.go
  pkg/restapi/common/store/cookie/api.go
  pkg/restapi/common/store/cookie/mock.go
  pkg/restapi/common/store/cookie/store.go
  pkg/restapi/common/store/helper.go
  pkg/restapi/common/store/tokens/store.go
  pkg/restapi/common/store/user/store.go
  pkg/restapi/oidc/dependencies.go
  pkg/restapi/oidc/helper.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  pkg/restapi/oidc/persistedData.go
  pkg/restapi/oidc/transientData.go
Labels: backend, cla-signed, refactor

#403 test: #385 login BDD test
  .gitignore
  Makefile
  ci/azure-pipelines.yml
  pkg/restapi/common/oidc/client.go
  scripts/check_httpserver_integration.sh
  scripts/generate_test_keys.sh
  test/bdd/bdd_test.go
  test/bdd/dockerutil/compose.go
  test/bdd/dockerutil/docker.go
  test/bdd/features/login.feature
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/docker-compose.yml
  test/bdd/fixtures/agent-wasm/hydra-config/hydra_configure.sh
  test/bdd/fixtures/agent-wasm/mysql-config/mysql_config.sql
  test/bdd/fixtures/agent-wasm/oidc-config/clients-config.json
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/mock/loginconsent/go.mod
  test/bdd/mock/loginconsent/go.sum
  test/bdd/mock/loginconsent/image/Dockerfile
  test/bdd/mock/loginconsent/main.go
  test/bdd/mock/loginconsent/server.go
  test/bdd/pkg/bddcontext/context.go
  test/bdd/pkg/login/steps.go
Labels: backend, cla-signed, test

#412 feat: webwallet blinded routing during didconnect - setup
  cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
  cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
  cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/user-agent/src/pages/chapi/wallet/index.js
  cmd/user-agent/src/pages/chapi/wallet/register/register.js
  cmd/user-agent/src/store/modules/user.js
Labels: cla-signed

#413 fix: #384 linters for BDD test package
  scripts/check_lint.sh
  test/bdd/bdd_test.go
  test/bdd/dockerutil/compose.go
  test/bdd/dockerutil/docker.go
  test/bdd/pkg/login/steps.go
Labels: bug, cla-signed

#414 chore: Hub-Router image version update
  test/bdd/fixtures/agent-wasm/.env
Labels: cla-signed

#416 fix: #384 lint of root Go module
  cmd/http-server/startcmd/start.go
  pkg/controller/command/api.go
  pkg/controller/command/credentialclient/command.go
  pkg/controller/command/credentialclient/command_test.go
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
  pkg/controller/command/didclient/models.go
  pkg/controller/command/errors.go
  pkg/controller/command/errors_test.go
  pkg/controller/command/internal/cmdutil/handler.go
  pkg/controller/command/internal/cmdutil/handler_test.go
  pkg/controller/command/presentationclient/command.go
  pkg/controller/command/presentationclient/command_test.go
  pkg/controller/command/sdscomm/messages.go
  pkg/controller/command/sdscomm/models.go
  pkg/controller/command/sdscomm/sdscomm.go
  pkg/controller/command/sdscomm/sdscomm_test.go
  pkg/controller/command/util.go
  pkg/controller/command/util_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/restapi/common/common.go
  pkg/restapi/common/common_test.go
  pkg/restapi/common/httphandler_test.go
  pkg/restapi/common/oidc/api.go
  pkg/restapi/common/oidc/client.go
  pkg/restapi/common/oidc/client_test.go
  pkg/restapi/common/oidc/mock.go
  pkg/restapi/common/oidc/mock_test.go
  pkg/restapi/common/store/cookie/api.go
  pkg/restapi/common/store/cookie/mock.go
  pkg/restapi/common/store/cookie/store.go
  pkg/restapi/common/store/helper.go
  pkg/restapi/common/store/tokens/store.go
  pkg/restapi/common/store/user/store.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  scripts/check_lint.sh
  test/user-agent/package-lock.json
Labels: bug, cla-signed

#415 feat: Multiple routers support
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/src/agent.js
  cmd/user-agent/src/components/Mediator/Mediator.vue
  cmd/user-agent/src/pages/chapi/wallet/common/didExchange.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
  cmd/user-agent/src/store/modules/connections.js
  cmd/user-agent/src/store/modules/mediator.js
  test/user-agent/test/wallet/walletCredentialQuery.spec.js
Labels: cla-signed

#418 feat: webwallet blinded routing - requesting peer DID from router
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
  cmd/user-agent/src/store/modules/user.js
  docs/test/test.md
  test/bdd/fixtures/agent-wasm/.env
Labels: cla-signed

#421 feat: webwallet blinded routing - request peer DID from other party
  Makefile
  cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
  cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/user-agent/src/store/modules/user.js
Labels: cla-signed

#422 chore: update trustbloc-did-method revision
  go.mod
  go.sum
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#423 feat: webwallet messaging correlate message replies
  cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
Labels: cla-signed

#427 test: fix race conditions in bdd tests
  test/user-agent/test/wallet/walletCredentialQuery.spec.js
Labels: cla-signed

#426 feat: webwallet js bddtests - blinded didconnect from issuer
  cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
  cmd/user-agent/src/store/modules/user.js
  test/user-agent/test/common.js
  test/user-agent/test/wallet/walletCredentialQuery.blinded.spec.js
  test/user-agent/test/wallet/walletCredentialQuery.spec.js
Labels: cla-signed

#428 feat: webwallet js bddtests - blinded didconnect from issuer
  cmd/user-agent/src/events/index.js
  test/user-agent/test/wallet/walletCredentialQuery.blinded.spec.js
Labels: cla-signed

#429 refactor: webwallet js bddtests - issuer and rp adapter mocks
  test/user-agent/test/mocks/adapters/issuerAdapter.js
  test/user-agent/test/mocks/index.js
  test/user-agent/test/wallet/walletCredentialQuery.blinded.spec.js
  test/user-agent/test/wallet/walletCredentialQuery.spec.js
Labels: cla-signed

#431 fix: codecov
  .gitignore
  scripts/check_unit.sh
Labels: cla-signed

#433 feat: webwallet blinded routing - correlation between msgs sent to issuer/RP
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/src/agent.js
  cmd/user-agent/src/pages/DIDManagement.vue
  cmd/user-agent/src/pages/TablePresentation.vue
  cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
  cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
  cmd/user-agent/src/pages/chapi/wallet/get/didAuth.js
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  go.mod
  test/user-agent/test/mocks/adapters/issuerAdapter.js
Labels: cla-signed

#435 chore: update to latest hub-router and message updates
  cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
  cmd/user-agent/src/store/modules/user.js
  test/bdd/fixtures/agent-wasm/.env
  test/user-agent/test/common.js
  test/user-agent/test/mocks/adapters/issuerAdapter.js
Labels: cla-signed

#436 feat: Uses agent-sdk
  Makefile
  ci/azp-dependencies.yml
  ci/azure-pipelines.yml
  cmd/agent-js-worker/.gitignore
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/main_test.go
  cmd/agent-js-worker/package-lock.json
  cmd/agent-js-worker/package.json
  cmd/agent-js-worker/scripts/build_assets.sh
  cmd/agent-js-worker/src/agent.js
  cmd/agent-js-worker/src/worker-impl-web.js
  cmd/agent-js-worker/src/worker-loader-web.js
  cmd/agent-js-worker/webpack.config.common.js
  cmd/agent-js-worker/webpack.config.web.js
  cmd/http-server/go.mod
  cmd/http-server/go.sum
  cmd/trustbloc-agent-js-worker/go.sum
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
  cmd/user-agent/scripts/setup_assets.sh
  cmd/user-agent/src/store/modules/options.js
  cmd/user-agent/src/store/modules/user.js
  cmd/user-agent/vue.config.js
  go.mod
  go.sum
  pkg/controller/command/api.go
  pkg/controller/command/credentialclient/command.go
  pkg/controller/command/credentialclient/command_test.go
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
  pkg/controller/command/didclient/models.go
  pkg/controller/command/errors.go
  pkg/controller/command/errors_test.go
  pkg/controller/command/internal/cmdutil/handler.go
  pkg/controller/command/internal/cmdutil/handler_test.go
  pkg/controller/command/internal/logutil/util.go
  pkg/controller/command/presentationclient/command.go
  pkg/controller/command/presentationclient/command_test.go
  pkg/controller/command/sdscomm/messages.go
  pkg/controller/command/sdscomm/models.go
  pkg/controller/command/sdscomm/sdscomm.go
  pkg/controller/command/sdscomm/sdscomm_test.go
  pkg/controller/command/util.go
  pkg/controller/command/util_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  scripts/build_agent_js_worker_wasm.sh
  scripts/check_js_integration.sh
  scripts/check_unit_wasm.sh
  test/user-agent/package-lock.json
  test/user-agent/package.json
  test/user-agent/scripts/setup_assets.sh
  test/user-agent/test/common.js
  test/user-agent/webpack.config.js
Labels: cla-signed

#439 ci: Fixes ci (Publish job)
  ci/azure-pipelines.yml
  docs/test/test.md
Labels: cla-signed

#440 fix: retry for router register
  cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js
Labels: cla-signed

#441 chore: fix security vulnerabilities
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
Labels: cla-signed

#442 chore: RP blinded routing enabled only for bddtests
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  test/user-agent/test/common.js
  test/user-agent/test/mocks/adapters/issuerAdapter.js
Labels: cla-signed

#443 fix: incorrect message types in blinded routing
  cmd/user-agent/src/store/modules/user.js
  test/user-agent/test/common.js
  test/user-agent/test/mocks/adapters/issuerAdapter.js
Labels: cla-signed

#444 feat: blinded routing - retries on failed 'diddoc-req'
  cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/blindedRouter.js
Labels: cla-signed

#445 feat: webwallet - retry msg send/reply on failed response
  cmd/user-agent/src/pages/chapi/wallet/common/messaging.js
Labels: cla-signed

#446 chore: update to latest agent-sdk
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
  cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
  test/user-agent/package-lock.json
  test/user-agent/package.json
Labels: cla-signed

#448 feat: webwallet - do not share DID from RP connection to issuer
  cmd/user-agent/src/pages/DIDManagement.vue
  cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/user-agent/src/pages/chapi/wallet/register/register.js
Labels: cla-signed

#450 fix: wallet's default DID showing up in demo1 DID list
  cmd/user-agent/src/pages/chapi/wallet/get/didAuth.js
Labels: cla-signed

#452 fix: Fixes createTrustBlocDID function
  cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
  scripts/check_js_integration.sh
  test/user-agent/package-lock.json
Labels: cla-signed

#451 chore: Updates agent-sdk version
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
  test/bdd/fixtures/agent-wasm/.env
  test/user-agent/package-lock.json
  test/user-agent/package.json
Labels: cla-signed

#453 feat: webwallet DID Comm flow - request for new RP DID
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/user-agent/src/store/modules/user.js
  test/user-agent/karma.conf.js
  test/user-agent/test/common.js
  test/user-agent/test/mocks/adapters/issuerAdapter.js
  test/user-agent/test/wallet/walletCredentialQuery.blinded.spec.js
  test/user-agent/test/wallet/walletCredentialQuery.spec.js
Labels: cla-signed

#456 feat: webwallet DIDComm - enable did doc req feature for RP
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
Labels: cla-signed

#457 fix: incorrect message type and retry on did doc request
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/user-agent/src/store/modules/user.js
Labels: cla-signed

#458 fix: webwallet to RP integration issue fix
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
Labels: cla-signed
