Repository trustbloc/wallet, pull requests merged in 2020-08, with the labels that each got.

#264 feat: Added dev mode
  cmd/user-agent/src/components/SidebarPlugin/SideBar.vue
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/Layout/DashboardLayout.vue
Labels: cla-signed

#272 feat: Added Relationships page
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/Layout/DashboardLayout.vue
  cmd/user-agent/src/pages/Relationships.vue
  cmd/user-agent/src/router/index.js
Labels: cla-signed, wip

#273 refactor: Added vuex
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
  cmd/user-agent/src/App.vue
  cmd/user-agent/src/components/CreateInvitation/CreateInvitation.vue
  cmd/user-agent/src/components/Mediator/Mediator.vue
  cmd/user-agent/src/components/PublicInvitation/PublicInvitation.vue
  cmd/user-agent/src/components/ReceiveInvitation/ReceiveInvitation.vue
  cmd/user-agent/src/components/SidebarPlugin/SideBar.vue
  cmd/user-agent/src/components/index.js
  cmd/user-agent/src/events/index.js
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/Connections.vue
  cmd/user-agent/src/pages/Layout/DashboardLayout.vue
  cmd/user-agent/src/pages/Relationships.vue
  cmd/user-agent/src/store/index.js
  cmd/user-agent/src/store/modules/connections.js
  cmd/user-agent/src/store/modules/init.js
  cmd/user-agent/src/store/modules/mediator.js
  cmd/user-agent/src/store/modules/mode.js
Labels: cla-signed

#270 feat: Plaintext DID storage in SDS
  .gitignore
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  cmd/trustbloc-agent-js-worker/go.sum
  cmd/trustbloc-agent-js-worker/main.go
  cmd/trustbloc-agent-js-worker/src/trustblocagent.js
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/DIDManagement.vue
  cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
  cmd/user-agent/src/pages/chapi/wallet/register/register.js
  cmd/user-agent/src/pages/chapi/wallet/register/walletManager.js
  docs/test/test.md
  go.mod
  go.sum
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
  pkg/controller/command/sdscomm/sdscomm.go
  pkg/controller/command/sdscomm/sdscomm_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/docker-compose.yml
  test/user-agent/test/common.js
Labels: cla-signed

#275 feat: Uses out-of-band protocol instead of didexchange
  cmd/user-agent/src/events/index.js
  cmd/user-agent/src/pages/chapi/wallet/common/didExchange.js
  cmd/user-agent/src/pages/chapi/wallet/didcomm/connections.js
  cmd/user-agent/src/pages/webWalletSamples.js
  cmd/user-agent/src/store/modules/mediator.js
  test/user-agent/test/common.js
  test/user-agent/test/wallet/walletCredentialQuery.spec.js
Labels: cla-signed

#277 refactor: Reuses components (Connections and Relationships pages)
  cmd/user-agent/src/components/Connections/Connections.vue
  cmd/user-agent/src/components/CopyButton/CopyButton.vue
  cmd/user-agent/src/components/CreateInvitation/CreateInvitation.vue
  cmd/user-agent/src/components/Mediator/Mediator.vue
  cmd/user-agent/src/components/PublicInvitation/PublicInvitation.vue
  cmd/user-agent/src/components/ReceiveInvitation/ReceiveInvitation.vue
  cmd/user-agent/src/components/index.js
  cmd/user-agent/src/pages/Connections.vue
  cmd/user-agent/src/pages/Layout/DashboardLayout.vue
  cmd/user-agent/src/pages/Relationships.vue
  cmd/user-agent/vue.config.js
Labels: cla-signed

#281 feat: credential mediators for CHAPI
  Makefile
  ci/azure-pipelines.yml
  ci/version_var.sh
  cmd/http-server/startcmd/start.go
  cmd/http-server/startcmd/start_test.go
  cmd/user-agent/public/worker.html
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/RegisterWallet.vue
  cmd/user-agent/src/pages/WebWallet.vue
  cmd/user-agent/src/pages/chapi/Get.vue
  cmd/user-agent/src/pages/chapi/Store.vue
  cmd/user-agent/src/pages/chapi/Worker.vue
  cmd/user-agent/src/pages/chapi/wallet/register/register.js
  cmd/user-agent/src/router/index.js
  docs/test/test.md
  images/credential-mediator/Dockerfile
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#278 feat: Uses secure connections (https,wss) to avoid Safari issue
  .gitignore
  cmd/user-agent/package.json
  cmd/user-agent/src/pages/webWalletSamples.js
  docs/test/test.md
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/docker-compose.yml
  test/user-agent/package.json
  test/user-agent/test/common.js
  test/user-agent/test/wallet/walletCredentialQuery.spec.js
Labels: cla-signed

#284 feat: TLS for credential mediators
  cmd/credential-mediator/configs/dev.js
  images/credential-mediator/Dockerfile
  scripts/generate_test_keys.sh
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#288 feat: Newer aries snapshot (label instead of did id)
  cmd/user-agent/package.json
  test/bdd/fixtures/agent-wasm/.env
  test/user-agent/package.json
Labels: cla-signed

#292 feat: custom CHAPI wizard
  cmd/credential-mediator/components/Mediator.vue
  images/credential-mediator/Dockerfile
Labels: cla-signed

#290 chore: update trustbloc-did-method dependency
  .gitignore
  Makefile
  cmd/trustbloc-agent-js-worker/go.sum
  cmd/user-agent/package-lock.json
  go.mod
  go.sum
  scripts/build-did-method-cli.sh
  scripts/check_js_intergation.sh
  scripts/generate_test_config.sh
  scripts/user_agent_start.sh
  test/bdd/fixtures/agent-wasm/config-data/config.json
  test/bdd/fixtures/agent-wasm/config-data/stakeholder.one_8088.json
  test/bdd/fixtures/agent-wasm/config-data/stakeholderone_jwk.json
  test/bdd/fixtures/agent-wasm/config-data/testnet.trustbloc.local.json
  test/bdd/fixtures/agent-wasm/discovery-compose.yml
  test/bdd/fixtures/agent-wasm/docker-compose.yml
  test/bdd/fixtures/agent-wasm/generate_config.sh
  test/bdd/fixtures/agent-wasm/run-uni-resolver-web.sh
Labels: cla-signed

#294 feat: CHAPI wizard custom empty state handling
  cmd/credential-mediator/components/Mediator.vue
  cmd/credential-mediator/configs/dev.js
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#295 feat: issuer manifest is matched if the credential schema uri is specified in a `const` filter
  cmd/user-agent/src/pages/chapi/wallet/common/presentationExchange.js
  test/user-agent/test/presentationDefQuery/presentationDef.spec.js
  test/user-agent/test/presentationDefQuery/testdata.js
Labels: cla-signed, enhancement

#299 chore: Revert "chore: update trustbloc-did-method dependency"
  .gitignore
  Makefile
  cmd/trustbloc-agent-js-worker/go.sum
  cmd/user-agent/package-lock.json
  go.mod
  go.sum
  scripts/build-did-method-cli.sh
  scripts/check_js_intergation.sh
  scripts/generate_test_config.sh
  scripts/user_agent_start.sh
  test/bdd/fixtures/agent-wasm/config-data/config.json
  test/bdd/fixtures/agent-wasm/config-data/stakeholder.one_8088.json
  test/bdd/fixtures/agent-wasm/config-data/stakeholderone_jwk.json
  test/bdd/fixtures/agent-wasm/config-data/testnet.trustbloc.local.json
  test/bdd/fixtures/agent-wasm/discovery-compose.yml
  test/bdd/fixtures/agent-wasm/docker-compose.yml
  test/bdd/fixtures/agent-wasm/generate_config.sh
  test/bdd/fixtures/agent-wasm/run-uni-resolver-web.sh
Labels: cla-signed

#297 fix: Added default SDS URL and agent username TrustBloc agent opts
  cmd/user-agent/src/main.js
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
  pkg/controller/command/sdscomm/sdscomm.go
  pkg/controller/command/sdscomm/sdscomm_test.go
Labels: cla-signed

#302 chore: remove credential mediator
  Makefile
  ci/azure-pipelines.yml
  ci/version_var.sh
  cmd/credential-mediator/components/Mediator.vue
  cmd/credential-mediator/configs/dev.js
  images/credential-mediator/Dockerfile
  scripts/generate_test_keys.sh
  test/bdd/fixtures/agent-wasm/.env
  test/bdd/fixtures/agent-wasm/docker-compose.yml
Labels: cla-signed

#307 fix: Presentations not being stored correctly in SDS
  cmd/user-agent/src/pages/chapi/wallet/store/saveCredential.js
Labels: cla-signed

#309 feat: didconnect to store credentials along with manifest
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/chapi/DIDConnect.vue
  cmd/user-agent/src/pages/chapi/Store.vue
  cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
  cmd/user-agent/src/pages/chapi/wallet/store/saveCredential.js
  cmd/user-agent/src/pages/webWalletSamples.js
  test/user-agent/test/common.js
  test/user-agent/test/wallet/walletCredentialQuery.spec.js
  test/user-agent/test/wallet/walletStore.spec.js
Labels: cla-signed

#312 feat: CHAPI didconnect view updates
  cmd/user-agent/src/pages/chapi/DIDConnect.vue
  cmd/user-agent/src/pages/chapi/Get.vue
  cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
Labels: cla-signed

#313 feat: Pre-fill friendly name of the credential while storing credential
  cmd/user-agent/src/pages/chapi/Store.vue
  test/user-agent/test/wallet/walletStore.spec.js
Labels: cla-signed

#314 feat: Adds associated credentials
  cmd/user-agent/package.json
  cmd/user-agent/src/components/AssociatedCredentials/AssociatedCredentials.vue
  cmd/user-agent/src/components/index.js
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/Relationships.vue
  cmd/user-agent/src/store/index.js
  cmd/user-agent/src/store/modules/credentials.js
  cmd/user-agent/src/store/modules/init.js
  go.mod
  go.sum
  test/bdd/fixtures/agent-wasm/.env
  test/user-agent/package.json
Labels: cla-signed

#315 fix: Filters credential with an empty label
  cmd/user-agent/src/store/modules/credentials.js
Labels: cla-signed

#318 feat: webwallet get user consent for sharing credentials over DIDComm
  cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
  cmd/user-agent/src/pages/chapi/wallet/common/util.js
  cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
Labels: cla-signed

#316 feat: Make SDS server URL and agent label optional for TrustBloc agent
  cmd/http-server/startcmd/start.go
  cmd/user-agent/src/main.js
  cmd/user-agent/src/pages/chapi/DIDConnect.vue
  cmd/user-agent/src/pages/chapi/Store.vue
  cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js
  cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
  cmd/user-agent/src/pages/chapi/wallet/store/saveCredential.js
  pkg/controller/command/credentialclient/command_test.go
  pkg/controller/command/didclient/command_test.go
  pkg/controller/command/presentationclient/command_test.go
  pkg/controller/command/sdscomm/messages.go
  pkg/controller/command/sdscomm/sdscomm.go
  pkg/controller/command/sdscomm/sdscomm_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: cla-signed

#321 feat: webwallet and governance framework integration
  cmd/user-agent/src/assets/img/govn.png
  cmd/user-agent/src/pages/WebWallet.vue
  cmd/user-agent/src/pages/chapi/DIDConnect.vue
  cmd/user-agent/src/pages/chapi/Governance.vue
  cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
  cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/user-agent/src/pages/webWalletSamples.js
Labels: cla-signed

#323 chore: follow up for user trust consent
  cmd/user-agent/src/pages/chapi/DIDConnect.vue
  cmd/user-agent/src/pages/chapi/Governance.vue
  cmd/user-agent/src/pages/chapi/PresentationDefQuery.vue
  cmd/user-agent/src/pages/chapi/wallet/get/didConn.js
  cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js
Labels: cla-signed

#324 chore: release v0.1.4
  ci/version_var.sh
  cmd/http-server/go.mod
  cmd/http-server/go.sum
  cmd/trustbloc-agent-js-worker/go.mod
  cmd/trustbloc-agent-js-worker/go.sum
  cmd/user-agent/package-lock.json
  cmd/user-agent/package.json
  go.mod
  go.sum
  test/bdd/fixtures/agent-wasm/.env
  test/user-agent/package-lock.json
  test/user-agent/package.json
Labels: cla-signed
