Repository trustbloc/wallet, pull requests merged in 2021-09, with the labels that each got.

#1014 chore: update to latest agent SDK
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1005 feat: Refactor credential preview json
  cmd/wallet-web/src/config/credentialDisplayData.js
  cmd/wallet-web/src/config/credentialDisplayData.json
  cmd/wallet-web/src/config/supportedLocales.js
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/mixins/common/helper.js
Labels: type: enhancement, cla-signed, area: UI

#1009 feat: Reusable credential detail UI component layout
  cmd/wallet-web/src/assets/img/more-icon.svg
  cmd/wallet-web/src/components/DIDManagement/CreateOrb.vue
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/components/Navbar/Navbar.vue
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/components/TabbedInterface/Tabs.vue
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/pages/DIDManagement.vue
  cmd/wallet-web/src/pages/Get.vue
  cmd/wallet-web/src/pages/demos/WebWallet.vue
  cmd/wallet-web/src/router/routes.js
  cmd/wallet-web/src/translations/Credentials/en.json
  cmd/wallet-web/src/translations/Credentials/fr.json
  cmd/wallet-web/src/translations/en.js
  cmd/wallet-web/src/translations/fr.js
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#1011 test: chapi get vc feat
  test/ui-automation/test/specs/credential-interaction-flow.js
Labels: cla-signed

#1018 fix: didcomm flow - credential function name
  cmd/wallet-web/src/pages/PresentationDefQuery.vue
Labels: cla-signed

#1020 feat: added routing logic for credential details screen
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/src/router/routes.js
Labels: type: enhancement, cla-signed, area: UI

#1021 feat: Populate fallback properties with vc credential subject
  cmd/wallet-web/src/pages/mixins/common/helper.js
Labels: cla-signed

#1024 fix: incorrect protocol handler reference in DIDComm flow
  cmd/wallet-web/src/pages/PresentationDefQuery.vue
Labels: cla-signed

#1026 refactor: refined credential page styles, switched to useBreakpoints
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/tailwind.js
Labels: type: refactor, area: UI

#1029 feat: implemented credential details banner component
  cmd/wallet-web/src/components/CredentialDetails/Banner.vue
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/src/translations/CredentialDetails/en.json
  cmd/wallet-web/src/translations/CredentialDetails/fr.json
  cmd/wallet-web/src/translations/Credentials/en.json
  cmd/wallet-web/src/translations/Credentials/fr.json
  cmd/wallet-web/src/translations/en.js
  cmd/wallet-web/src/translations/fr.js
Labels: type: enhancement, cla-signed, area: UI

#1037 chore: update agent-sdk dependency
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1033 feat: Integrate credential details screen with the processed credential array
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/mixins/common/helper.js
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed

#1038 fix: Credential detail on refresh fails to get processed credential and render base64 image
  cmd/wallet-web/src/config/credentialDisplayData.js
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed

#1040 chore: set agent-sdk and wallet-sdk to fixed version
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1043 feat: integrated credential details banner with real data
  cmd/wallet-web/src/components/CredentialDetails/Banner.vue
  cmd/wallet-web/src/config/credentialDisplayData.js
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/pages/mixins/common/helper.js
Labels: type: enhancement, cla-signed, area: UI

#1044 fix: fixed navbar height issue, implemented mobile design
  cmd/wallet-web/src/components/CredentialDetails/Banner.vue
  cmd/wallet-web/src/components/Navbar/Navbar.vue
  cmd/wallet-web/src/pages/CredentialDetails.vue
Labels: type: enhancement, area: UI

#1045 feat: WACI Share - introducing wait for present proof msg deliver
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/src/pages/mixins/common/helper.js
  cmd/wallet-web/src/pages/mixins/handler/waci.js
Labels: cla-signed

#1046 chore: disable remote context download for wallet agent wasm
  cmd/wallet-web/src/store/modules/options.js
  test/fixtures/wallet-web/docker-compose-web.yml
Labels: cla-signed

#1049 refactor: created reusable component for credential preview
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
  cmd/wallet-web/src/pages/Dashboard.vue
Labels: cla-signed, type: refactor, area: UI

#1041 feat: js schema-uri matching now parses json-ld contexts for cred type IDs
  cmd/wallet-web/src/pages/mixins/common/helper.js
  cmd/wallet-web/src/pages/mixins/common/presentationExchange.js
  cmd/wallet-web/test/fixtures/testdata/contexts/agent-startup-contexts.json
  cmd/wallet-web/test/specs/presexch.spec.js
Labels: cla-signed

#1050 feat: Add manifest for CMTR and crude Product oil credentials
  cmd/wallet-web/src/config/credentialDisplayData.js
Labels: cla-signed

#1053 feat: added brand colors, hover and focus states to credential preview
  cmd/wallet-web/src/assets/img/credential--arrow-right-icon-light.svg
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
  cmd/wallet-web/src/config/credentialDisplayData.js
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/mixins/common/helper.js
  cmd/wallet-web/tailwind.js
Labels: type: enhancement, cla-signed, type: refactor, area: UI

#1058 feat: added authentic icons to supported types of credentials
  cmd/wallet-web/src/assets/img/credential--flight-icon.svg
  cmd/wallet-web/src/assets/img/credential--school-icon.svg
  cmd/wallet-web/src/assets/img/credential--uscis-icon.svg
  cmd/wallet-web/src/assets/img/credential--vaccination-icon.svg
  cmd/wallet-web/src/assets/img/credential-drivers-license-icon.svg
  cmd/wallet-web/src/config/credentialDisplayData.js
  cmd/wallet-web/src/config/supportedLocales.js
Labels: type: enhancement, cla-signed, area: UI

#1059 fix: waci integration issue
  cmd/wallet-web/src/pages/WACIShare.vue
Labels: cla-signed

#1060 feat: disable CHAPI for mobile browsers
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
Labels: cla-signed

#1056 feat: Chapi DID Auth updated UI
  cmd/wallet-web/alias.config.js
  cmd/wallet-web/src/assets/img/generic-issuer-icon.svg
  cmd/wallet-web/src/assets/img/share.svg
  cmd/wallet-web/src/assets/img/small-lock-icon.svg
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/pages/DIDAuth.vue
  cmd/wallet-web/src/pages/Get.vue
  cmd/wallet-web/src/router/routes.js
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#1063 chore: updated favicon
  cmd/wallet-web/.gitignore
  cmd/wallet-web/public/favicon.png
  cmd/wallet-web/public/index.html
  cmd/wallet-web/public/logo.png
  cmd/wallet-web/src/components/Logo/Logo.vue
Labels: cla-signed, type: chore, area: UI

#1065 feat: added brand colors and dynamic icons to credential details banner
  cmd/wallet-web/src/components/CredentialDetails/Banner.vue
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/router/routes.js
Labels: type: enhancement, cla-signed, area: UI

#1068 fix: disable error display for DIDAuth query failure
  cmd/wallet-web/src/pages/DIDAuth.vue
Labels: cla-signed

#1070 chore: Configure Booking reference VC
  Makefile
  cmd/wallet-web/src/config/credentialDisplayData.js
  cmd/wallet-web/src/pages/demos/webWalletSamples.js
  test/ui-automation/test/specs/credential-interaction-flow.js
Labels: cla-signed

#1072 chore: increase WACI share wait before redirect
  cmd/wallet-web/src/pages/WACIShare.vue
Labels: cla-signed

#1074 feat: Chapi save credentials UI change
  cmd/wallet-web/src/components/CredentialDetails/Banner.vue
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/src/translations/CredentialDetails/en.json
  cmd/wallet-web/src/translations/CredentialDetails/fr.json
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#1078 ci: increase publish job timeout
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: cla-signed

#1076 feat: implemented new designs for chapi share page
  cmd/wallet-web/src/assets/img/icons-warning.svg
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/MultipleQuery.vue
  cmd/wallet-web/src/translations/CHAPI/en.json
  cmd/wallet-web/src/translations/CHAPI/fr.json
  cmd/wallet-web/src/translations/en.js
  cmd/wallet-web/src/translations/fr.js
  cmd/wallet-web/test/specs/get.spec.js
Labels: type: enhancement, cla-signed, area: UI

#1079 chore: CHAPI manifest JSON
  cmd/wallet-web/public/favicon.ico
  cmd/wallet-web/public/manifest.json
  images/wallet-web/templates/default.conf.template
  test/ui-automation/wdio.conf.js
Labels: cla-signed

#1084 fix: fixed skeleton loader width issue
  cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoader.vue
  cmd/wallet-web/src/components/SkeletonLoader/VaultCard.vue
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/tailwind.js
Labels: cla-signed, type: fix, area: UI

#1082 feat: MongoDB support for wallet-server
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-server/startcmd/agentconfig.go
  cmd/wallet-server/startcmd/start.go
  cmd/wallet-server/startcmd/start_test.go
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
Labels: type: enhancement, cla-signed, area: backend

#1087 fix: blank dashboard during re-login
  cmd/wallet-web/public/manifest.json
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/store/modules/user.js
  test/ui-automation/wdio.conf.js
Labels: cla-signed

#1085 chore: update agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1089 feat: updated waci share component with the new designs
  cmd/wallet-web/src/pages/MultipleQuery.vue
  cmd/wallet-web/src/pages/WACIShare.vue
Labels: type: enhancement, cla-signed, area: UI

#1094 feat: implemented new design for credential details in CHAPI share flow
  cmd/wallet-web/src/config/credentialDisplayData.js
  cmd/wallet-web/src/pages/MultipleQuery.vue
  cmd/wallet-web/src/pages/mixins/common/helper.js
Labels: type: enhancement, cla-signed, area: UI

#1097 refactor: adjust waci share for rendering outside of iframe
  cmd/wallet-web/src/pages/WACIShare.vue
Labels: type: enhancement, cla-signed, area: UI

#1093 feat: WACI redirect enhancements
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/router/routes.js
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed

#1098 fix: WACI integration issues
  cmd/wallet-web/src/pages/WACIShare.vue
Labels: cla-signed

#1099 chore: update bdd test images to release
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-web.yml
Labels: cla-signed

#1100 fix: query params for signin redirect
  cmd/wallet-web/src/pages/Signin.vue
Labels: cla-signed

#1102 fix: Fix the background colour change issue in save credential
  cmd/wallet-web/src/pages/Store.vue
Labels: cla-signed

#1103 fix: fixed waci share layout
  cmd/wallet-web/src/pages/WACIShare.vue
Labels: cla-signed, type: fix, area: UI

#1088 chore: udpate latest deps
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/WACIShare.vue
  go.mod
  go.sum
  test/fixtures/wallet-web/.env
  test/mock/demo-login-consent-server/go.mod
  test/mock/demo-login-consent-server/go.sum
Labels: cla-signed

#1105 chore: update to latest agent-sdk-web and wallet-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/fixtures/wallet-web/.env
Labels: cla-signed

#1110 ci: add lfs tag to release build
  .github/workflows/publish.yml
Labels: cla-signed

#1112 fix: Refactor toggle solution in store vue
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/test/specs/store.spec.js
Labels: cla-signed

#1116 fix: fixed CHAPI store height issue
  cmd/wallet-web/src/pages/Store.vue
Labels: cla-signed, type: fix, area: UI

#1120 feat: added success message and more
  cmd/wallet-web/src/components/DIDManagement/Preferences.vue
  cmd/wallet-web/src/components/Spinner/Spinner.vue
  cmd/wallet-web/src/components/StyledButton/StyledButton.vue
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/tailwind.js
Labels: type: enhancement, cla-signed, area: UI

#1123 test: [ui-automation] credential details screen
  Makefile
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/credential-interaction-flow.js
Labels: cla-signed

#1125 fix: Removing register device from Wallet
  cmd/wallet-web/src/pages/RegisterDevice.vue
Labels: cla-signed

#1126 ci: push wallet-server before wallet-web
  .github/workflows/build.yml
  .github/workflows/publish.yml
  Makefile
Labels: cla-signed

#1128 test: [ui-automation] support for ES modules
  test/ui-automation/babel.config.js
  test/ui-automation/package-lock.json
  test/ui-automation/package.json
  test/ui-automation/test/helpers/index.js
  test/ui-automation/test/specs/credential-interaction-flow.js
  test/ui-automation/wdio.conf.js
  test/ui-automation/wdio.shared.conf.js
Labels: cla-signed

#1132 test: mock demo adapter setup
  .github/workflows/build.yml
  Makefile
  docs/test/test.md
  scripts/generate_test_keys.sh
  scripts/run_ui_automation.sh
  scripts/wallet_web_dev_start.sh
  scripts/wallet_web_start.sh
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-demo.yml
  test/fixtures/wallet-web/docker-compose-web.yml
  test/mock/adapter/common.go
  test/mock/adapter/didcomm.go
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
  test/mock/adapter/image/Dockerfile
  test/mock/adapter/main.go
  test/mock/adapter/templates/verifier.html
  test/mock/adapter/verifier.go
Labels: cla-signed

#1135 fix: Add the spinner to the button click
  test/mock/demo-login-consent-server/templates/login.html
Labels: type: enhancement, cla-signed, area: UI

#1138 refactor: refactored BlockNoAuth component
  cmd/wallet-web/src/pages/BlockNoAuth.vue
  cmd/wallet-web/src/router/routes.js
Labels: cla-signed, type: refactor, area: UI

#1129 refactor: refactored presentation def query
  cmd/wallet-web/src/pages/Governance.vue
  cmd/wallet-web/src/pages/MultipleQuery.vue
  cmd/wallet-web/src/pages/PresentationDefQuery.vue
Labels: cla-signed, type: refactor, area: UI

#1139 test: [ui-automation] WACI Share
  .github/workflows/build.yml
  scripts/run_ui_automation.sh
  test/fixtures/wallet-web/docker-compose-demo.yml
  test/mock/adapter/didcomm.go
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
  test/mock/adapter/main.go
  test/mock/adapter/templates/verifier.html
  test/mock/adapter/verifier.go
  test/ui-automation/package-lock.json
  test/ui-automation/package.json
  test/ui-automation/test/specs/waci-flow.js
  test/ui-automation/wdio.conf.js
  test/ui-automation/wdio.shared.conf.js
Labels: cla-signed

#1142 test: waci-share - validate credential details
  test/ui-automation/test/specs/waci-flow.js
Labels: cla-signed

#1144 feat: added on key enter even handler for some ui elements
  cmd/wallet-web/src/components/Navbar/NavbarLink.vue
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
Labels: type: enhancement, cla-signed, area: UI

#1145 fix: potential fix for issuers not showing up in DIDComm share flow component
  cmd/wallet-web/src/pages/PresentationDefQuery.vue
Labels: type: fix, area: UI
