Repository trustbloc/wallet, pull requests merged in 2021-08, with the labels that each got.

#893 test: basic user flow test
  .github/workflows/build.yml
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/signup.js
  test/ui-automation/test/specs/user-flow.js
  test/ui-automation/wdio.shared.conf.js
Labels: cla-signed

#894 fix: cookie issues
  cmd/wallet-web/src/store/modules/options.js
  pkg/restapi/common/store/cookie/store.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
Labels: cla-signed

#880 feat: setup localized routes
  cmd/wallet-web/src/App.vue
  cmd/wallet-web/src/EventBus.js
  cmd/wallet-web/src/components/LocaleSwitcher/LocaleSwitcher.vue
  cmd/wallet-web/src/config/supportedLocales.js
  cmd/wallet-web/src/i18n.js
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/pages/Logout.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/layout/ContentFooter.vue
  cmd/wallet-web/src/plugins/i18n.js
  cmd/wallet-web/src/router/Root.vue
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/router/routes.js
  cmd/wallet-web/src/store/index.js
  cmd/wallet-web/src/store/modules/locale.js
  cmd/wallet-web/src/translations/en.json
  cmd/wallet-web/src/translations/fr.json
  cmd/wallet-web/src/utils/i18n/getBrowserLocale.js
  cmd/wallet-web/vue.config.js
Labels: enhancement, cla-signed

#897 feat: Add reusable Toast Component
  cmd/wallet-web/src/assets/img/close-icon.svg
  cmd/wallet-web/src/assets/img/triangle-exclamation.svg
  cmd/wallet-web/src/components/ToastNotification/ToastNotification.vue
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/translations/en.json
  cmd/wallet-web/src/translations/fr.json
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#903 fix: fixed router history issue
  cmd/wallet-web/src/components/LocaleSwitcher/LocaleSwitcher.vue
  cmd/wallet-web/src/pages/BlockNoAuth.vue
  cmd/wallet-web/src/pages/Logout.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/router/index.js
Labels: cla-signed, refactor

#904 feat: added eslint and prettier checks to CI
  .github/workflows/build.yml
  Makefile
Labels: enhancement, cla-signed

#906 fix: fixed issue with second time sign in/up
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed, refactor

#908 feat: added prettier and eslint to publish requirements
  .github/workflows/build.yml
Labels: enhancement, cla-signed

#909 chore: removed sweetalert2 from /cmd/wallet-web
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed, chore

#913 refactor: removed old Login component
  cmd/wallet-web/src/pages/Login.vue
  cmd/wallet-web/src/router/routes.js
Labels: cla-signed, refactor

#915 feat: Integrate toast notification for system failures and remove loader on closed popup
  cmd/wallet-web/src/pages/LoginHandle.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/store/index.js
  cmd/wallet-web/src/store/modules/user.js
  cmd/wallet-web/src/translations/en.json
  cmd/wallet-web/src/translations/fr.json
Labels: cla-signed

#920 fix: fixed path to ui automation package file
  .github/dependabot.yml
Labels: cla-signed, fix

#911 feat: added pre-commit hook
  .husky/.gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: enhancement, cla-signed

#923 refactor: added some improvements to i18n setup
  cmd/wallet-web/package.json
  cmd/wallet-web/src/plugins/i18n.js
  cmd/wallet-web/src/translations/App/en.json
  cmd/wallet-web/src/translations/App/fr.json
  cmd/wallet-web/src/translations/ContentFooter/en.json
  cmd/wallet-web/src/translations/ContentFooter/fr.json
  cmd/wallet-web/src/translations/Signin/en.json
  cmd/wallet-web/src/translations/Signin/fr.json
  cmd/wallet-web/src/translations/Signup/en.json
  cmd/wallet-web/src/translations/Signup/fr.json
  cmd/wallet-web/src/translations/en.js
  cmd/wallet-web/src/translations/en.json
  cmd/wallet-web/src/translations/fr.js
  cmd/wallet-web/src/translations/fr.json
Labels: cla-signed, refactor, fix

#938 feat: added temporary path for the new dashboard
  cmd/wallet-web/src/pages/DashboardV2.vue
  cmd/wallet-web/src/pages/layout/DashboardLayoutV2.vue
  cmd/wallet-web/src/router/routes.js
Labels: enhancement, cla-signed

#940 fix: fixed imports in routes
  cmd/wallet-web/src/router/routes.js
Labels: cla-signed, fix

#942 feat: Responsive vault card skeleton loader
  cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoader.vue
  cmd/wallet-web/src/components/SkeletonLoader/VaultCard.vue
  cmd/wallet-web/src/components/ToastNotification/ToastNotification.vue
  cmd/wallet-web/src/pages/DashboardV2.vue
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#945 test: added automation test for localization logic
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/user-flow.js
Labels: cla-signed, test, fix

#949 feat: added new package files to Dependabot config
  .github/dependabot.yml
Labels: cla-signed, area: DX

#951 feat: Update the existing credential cards components with config file
  cmd/wallet-web/src/config/credentialDisplayData.json
  cmd/wallet-web/src/pages/DashboardV2.vue
Labels: cla-signed

#954 feat: added on hover styles to the new sidebar
  cmd/wallet-web/src/components/SidebarPluginV2/SideBarV2.vue
  cmd/wallet-web/src/components/SidebarPluginV2/SidebarLinkV2.vue
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/pages/DashboardV2.vue
  cmd/wallet-web/tailwind.js
Labels: type: enhancement, cla-signed, area: UI

#960 fix: add exit code for ui-automation
  scripts/run_ui_automation.sh
Labels: cla-signed

#957 refactor: removed old dashboard and switched to the new one
  cmd/wallet-web/src/components/SidebarPlugin/SideBar.vue
  cmd/wallet-web/src/components/SidebarPlugin/Sidebar.vue
  cmd/wallet-web/src/components/SidebarPlugin/SidebarLink.vue
  cmd/wallet-web/src/components/SidebarPlugin/index.js
  cmd/wallet-web/src/components/SidebarPluginV2/SidebarLinkV2.vue
  cmd/wallet-web/src/components/SidebarPluginV2/index.js
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/material-dashboard.js
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/DashboardV2.vue
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/src/pages/layout/DashboardLayoutV2.vue
  cmd/wallet-web/src/router/routes.js
  test/ui-automation/test/helpers/wallet.js
Labels: cla-signed, type: refactor, area: UI

#964 feat: added underline styles to sidebar footer links
  cmd/wallet-web/src/components/SidebarPlugin/Sidebar.vue
  cmd/wallet-web/tailwind.js
Labels: type: enhancement, cla-signed, area: UI

#967 refactor: moved chapi screens outside of the dashboard layout route
  cmd/wallet-web/src/pages/Logout.vue
  cmd/wallet-web/src/pages/layout/TopNavbar.vue
  cmd/wallet-web/src/router/routes.js
  docs/components/wallet_web.md
  test/ui-automation/test/specs/user-flow.js
Labels: cla-signed, type: refactor, area: UI

#966 feat: added focus styles to sidebar links
  cmd/wallet-web/src/components/LocaleSwitcher/LocaleSwitcher.vue
  cmd/wallet-web/src/components/Logo/Logo.vue
  cmd/wallet-web/src/components/SidebarPlugin/Sidebar.vue
  cmd/wallet-web/src/components/SidebarPlugin/SidebarLink.vue
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/layout/Header.vue
  cmd/wallet-web/tailwind.js
Labels: type: enhancement, cla-signed, area: UI

#971 feat: implemented mobile header, removed unused components
  cmd/wallet-web/src/assets/img/header-mobile-flare.png
  cmd/wallet-web/src/assets/img/menu-icon.svg
  cmd/wallet-web/src/assets/img/navbar-flare.png
  cmd/wallet-web/src/assets/img/sidebar-2.jpg
  cmd/wallet-web/src/components/Footer/Footer.vue
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/components/Navbar/Navbar.vue
  cmd/wallet-web/src/components/Navbar/NavbarLink.vue
  cmd/wallet-web/src/components/Navbar/index.js
  cmd/wallet-web/src/components/SidebarPlugin/index.js
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/material-dashboard.js
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/layout/Content.vue
  cmd/wallet-web/src/pages/layout/DashboardContent.vue
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/src/pages/layout/MobileMenu.vue
  cmd/wallet-web/src/pages/layout/TopNavbar.vue
  cmd/wallet-web/src/translations/Footer/en.json
  cmd/wallet-web/src/translations/Footer/fr.json
  cmd/wallet-web/src/translations/en.js
  cmd/wallet-web/src/translations/fr.js
  cmd/wallet-web/tailwind.js
Labels: type: enhancement, cla-signed, area: UI

#973 feat: Add credential preview as per UX design
  cmd/wallet-web/src/assets/img/credential--arrow-right-icon.svg
  cmd/wallet-web/src/assets/img/credential--generic-icon.svg
  cmd/wallet-web/src/assets/img/credential--school-icon.svg
  cmd/wallet-web/src/config/credentialDisplayData.json
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#980 feat: Adding body shadows and credential detail layout for desktop
  cmd/wallet-web/src/App.vue
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#983 fix: Temporary fix for the credential preview and add random unique email for login
  cmd/wallet-web/src/pages/Dashboard.vue
  test/mock/demo-login-consent-server/templates/login.html
Labels: cla-signed

#984 docs: user preferences & did management
  docs/components/wallet_web.md
Labels: cla-signed

#987 chore: hub-auth update to hub-auth:0.1.7-snapshot-f9b282e
  test/fixtures/wallet-web/.env
  test/mock/demo-login-consent-server/main.go
Labels: cla-signed

#986 feat: Add "No credentials yet" screen
  cmd/wallet-web/src/assets/img/icons-md--credentials-icon.svg
  cmd/wallet-web/src/assets/img/icons-sm--chevron-down-icon.svg
  cmd/wallet-web/src/assets/img/icons-sm--vault-icon.svg
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/src/translations/Credentials/en.json
  cmd/wallet-web/src/translations/Credentials/fr.json
  cmd/wallet-web/src/translations/en.js
  cmd/wallet-web/src/translations/fr.js
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#991 feat: Add the focus and responsive credential preview screen
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/src/translations/Credentials/en.json
  cmd/wallet-web/src/translations/Credentials/fr.json
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#992 feat: No credential found screen mobile responsive and fix login bank issue
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/tailwind.js
  test/mock/demo-login-consent-server/main.go
Labels: cla-signed

#1007 feat: WACI redirect support in webwallet
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/Get.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/WACI.vue
  cmd/wallet-web/src/pages/mixins/handler/waci.js
  cmd/wallet-web/src/router/index.js
Labels: cla-signed
