Repository trustbloc/wallet, pull requests merged in 2021-11, with the labels that each got.

#1195 feat: wallet web ui tests for WACI ack redirect
  test/fixtures/wallet-web/docker-compose-demo.yml
  test/mock/adapter/common.go
  test/mock/adapter/didcomm.go
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
  test/mock/adapter/main.go
  test/mock/adapter/verifier.go
Labels: cla-signed

#1199 feat: Refactor vault card mobile and desktop , Add default vault and address warnings
  cmd/wallet-web/src/assets/img/icons-sm--plus-icon.svg
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenuList.vue
  cmd/wallet-web/src/components/VaultCard/VaultCard.vue
  cmd/wallet-web/src/pages/PageNotFound.vue
  cmd/wallet-web/src/pages/PresentationDefQuery.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/Vaults.vue
  cmd/wallet-web/src/translations/Vaults/en.json
  cmd/wallet-web/src/translations/Vaults/fr.json
  cmd/wallet-web/tailwind.js
Labels: type: enhancement, cla-signed, area: UI

#1206 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/components/DIDManagement/CreateOrb.vue
  cmd/wallet-web/src/components/DIDManagement/ImportDid.vue
  cmd/wallet-web/src/components/DIDManagement/Preferences.vue
  cmd/wallet-web/src/pages/mixins/common/register.js
  cmd/wallet-web/src/pages/mixins/get/getCredentialsByQuery.js
  cmd/wallet-web/test/common.js
Labels: cla-signed

#1212 chore: add log msg
  cmd/wallet-web/src/pages/mixins/common/register.js
Labels: cla-signed

#1214 fix: check equivalent id array length
  cmd/wallet-web/src/pages/mixins/common/register.js
Labels: cla-signed

#1215 fix: equivalentId array check
  cmd/wallet-web/src/pages/mixins/common/register.js
Labels: cla-signed

#1216 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1217 fix: mediator issues in dev mode
  cmd/wallet-web/src/store/modules/options.js
Labels: cla-signed

#1218 chore: update to latest agent sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1220 chore: update to latest agent sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1221 chore: update to latest agent sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1223 chore: update to latest agent sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1225 chore: update to latest agent sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/mixins/common/register.js
Labels: cla-signed

#1224 feat: Add vault implementation
  cmd/wallet-web/src/assets/img/Icons-sm--close-icon.svg
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenuList.vue
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/src/components/Modal/AddVault.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/Vaults.vue
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/src/translations/Vaults/en.json
  cmd/wallet-web/src/translations/Vaults/fr.json
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#1228 fix: Fix the French name rendering issue for All Vault in credential
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
  cmd/wallet-web/src/translations/CredentialDetails/fr.json
Labels: cla-signed

#1229 feat: add unanchoredDIDMaxLifeTime flag
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/options.js
Labels: cla-signed

#1231 fix: Refactor Fetch All Vault logic
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/src/pages/Vaults.vue
Labels: cla-signed

#1238 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1239 fix: getAllDID returning uninform data
  cmd/wallet-web/src/components/DIDManagement/CreateOrb.vue
  cmd/wallet-web/src/components/DIDManagement/ImportDid.vue
  cmd/wallet-web/src/components/DIDManagement/Preferences.vue
Labels: cla-signed

#1244 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1246 fix: use base64url encoding for credential id
  cmd/wallet-web/src/pages/mixins/common/helper.js
Labels: cla-signed, type: fix, area: UI

#1249 fix: use raw value with web workers api
  cmd/wallet-web/src/pages/DIDAuth.vue
  cmd/wallet-web/src/pages/MultipleQuery.vue
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/src/pages/mixins/handler/chapi.js
Labels: cla-signed, type: fix, area: UI

#1252 docs: update repo name in the documentation
  docs/dev/dev-mode.md
  docs/test/test.md
  test/fixtures/wallet-web/mysql-config/mysql_config.sql
Labels: cla-signed

#1237 feat: Link save credentials with Vault
  cmd/wallet-web/src/components/CustomSelect/CustomSelect.vue
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/src/components/Modal/AddVault.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/src/pages/Vaults.vue
  cmd/wallet-web/src/pages/mixins/common/register.js
  cmd/wallet-web/src/translations/Vaults/en.json
  cmd/wallet-web/src/translations/Vaults/fr.json
Labels: cla-signed

#1255 refactor: updated unit tests setup
  Makefile
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/test/common.js
  cmd/wallet-web/test/specs/get.spec.js
  cmd/wallet-web/test/specs/store.spec.js
  cmd/wallet-web/webpack.test.js
  test/ui-automation/package-lock.json
  test/ui-automation/package.json
Labels: cla-signed, type: refactor, area: unit tests

#1264 chore: upgraded ui automation deps
  test/ui-automation/package-lock.json
  test/ui-automation/package.json
Labels: cla-signed, type: chore, area: integration tests

#1263 feat: added error handling for add vault logic
  cmd/wallet-web/src/components/Modal/AddVault.vue
Labels: type: enhancement, cla-signed, area: UI

#1262 refactor: renamed dashboard screen to credentials, set vaults as default route
  cmd/wallet-web/src/components/CustomSelect/CustomSelect.vue
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenuList.vue
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/components/Navbar/NavbarLink.vue
  cmd/wallet-web/src/pages/Credentials.vue
  cmd/wallet-web/src/pages/PageNotFound.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/src/router/routes.js
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/credential-interaction-flow.js
  test/ui-automation/test/specs/waci-flow.js
Labels: cla-signed, type: refactor, area: UI

#1265 feat: enabled css purging for production, updated styles in adapter
  cmd/wallet-web/src/components/Navbar/Navbar.vue
  cmd/wallet-web/src/components/Navbar/NavbarLink.vue
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/tailwind.js
  test/mock/adapter/templates/css/styles.css
Labels: type: enhancement, cla-signed, area: UI

#1268 fix: Fix the selected default in the dropdown to save cred in default cred
  cmd/wallet-web/src/pages/Store.vue
Labels: type: enhancement, cla-signed, area: UI
