Repository trustbloc/wallet, pull requests merged in 2021-03, with the labels that each got.

#670 feat: Use new Aries storage implementations, remove edge-core storage
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-server/startcmd/agentconfig.go
  cmd/wallet-server/startcmd/start.go
  cmd/wallet-server/startcmd/start_test.go
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/chapi/wallet/common/keyValStore.js
  go.mod
  go.sum
  pkg/restapi/common/store/helper.go
  pkg/restapi/common/store/tokens/store.go
  pkg/restapi/common/store/user/store.go
  pkg/restapi/device/operations.go
  pkg/restapi/device/operations_test.go
  pkg/restapi/internal/mocks/protocol/provider.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/mock/bddtest-login-consent-server/go.mod
  test/bdd/mock/bddtest-login-consent-server/go.sum
  test/bdd/mock/bddtest-login-consent-server/main.go
  test/bdd/mock/bddtest-login-consent-server/server.go
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#672 chore: upgrade dependencies
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  go.mod
  go.sum
  pkg/restapi/oidc/webkms.go
  pkg/restapi/oidc/webkms_test.go
  test/bdd/go.sum
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#673 chore: update trustbloc-did-method
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-server/startcmd/agentconfig.go
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/bdd/fixtures/wallet-web/.env
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#675 feat: selective disclosure in webwallet
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/WebWallet.vue
  cmd/wallet-web/src/pages/chapi/Get.vue
  cmd/wallet-web/src/pages/chapi/QueryByFrame.vue
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByFrame.js
  cmd/wallet-web/src/pages/chapi/wallet/index.js
  cmd/wallet-web/src/pages/webWalletSamples.js
  cmd/wallet-web/src/store/modules/options.js
  test/bdd/fixtures/wallet-web/.env
  test/bdd/mock/demo-login-consent-server/go.sum
Labels: cla-signed

#676 chore: Update EDV Docker image
  test/bdd/fixtures/wallet-web/.env
Labels: cla-signed

#678 fix: EDV Docker image version
  test/bdd/fixtures/wallet-web/.env
Labels: cla-signed

#677 feat: Re-add LevelDB option for wallet-server
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-server/startcmd/agentconfig.go
  cmd/wallet-server/startcmd/start.go
  cmd/wallet-server/startcmd/start_test.go
Labels: cla-signed

#679 chore: Update aries-framework-go-ext commit versions
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
Labels: cla-signed

#680 chore: update to latest aries
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByFrame.js
  cmd/wallet-web/src/pages/webWalletSamples.js
  go.mod
  go.sum
  test/bdd/go.sum
  test/bdd/mock/bddtest-login-consent-server/go.mod
  test/bdd/mock/bddtest-login-consent-server/go.sum
  test/bdd/mock/demo-login-consent-server/go.sum
Labels: cla-signed

#681 chore: release v0.1.6
  ci/version_var.sh
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  go.mod
  go.sum
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/config-data/stakeholder.one_8088.json
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/mock/bddtest-login-consent-server/go.mod
  test/bdd/mock/bddtest-login-consent-server/go.sum
  test/bdd/mock/demo-login-consent-server/go.mod
  test/bdd/mock/demo-login-consent-server/go.sum
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#682 chore: complete release v0.1.6
  ci/version_var.sh
Labels: cla-signed

#685 chore: make session cookie max age configurable
  cmd/wallet-server/startcmd/start.go
  cmd/wallet-server/startcmd/start_test.go
  pkg/restapi/common/store/cookie/store.go
  pkg/restapi/device/operations.go
  pkg/restapi/device/operations_test.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
Labels: chore, cla-signed

#686 chore: update latest dependencies
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  go.mod
  go.sum
  test/bdd/fixtures/wallet-web/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/bdd/mock/bddtest-login-consent-server/go.mod
  test/bdd/mock/bddtest-login-consent-server/go.sum
  test/bdd/mock/demo-login-consent-server/go.mod
  test/bdd/mock/demo-login-consent-server/go.sum
Labels: cla-signed

#687 chore: update agent-sdk revision
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/scripts/setup_assets.sh
  cmd/wallet-web/src/store/modules/user.js
  cmd/wallet-web/vue.config.js
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
  test/wallet-web/scripts/setup_assets.sh
  test/wallet-web/test/common.js
  test/wallet-web/webpack.config.js
Labels: cla-signed

#688 feat: wallet UI - flattening selective dislcosure data
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/WebWallet.vue
  cmd/wallet-web/src/pages/chapi/MultipleQuery.vue
  cmd/wallet-web/src/pages/chapi/wallet/get/multiQuery.js
  cmd/wallet-web/src/pages/webWalletSamples.js
Labels: cla-signed

#698 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#694 refactor: update presentation-exchange impl
  cmd/wallet-web/src/pages/chapi/wallet/common/presentationDefSchema.js
  cmd/wallet-web/src/pages/chapi/wallet/common/presentationExchange.js
  test/wallet-web/test/presentationDefQuery/presentationDef.spec.js
  test/wallet-web/test/presentationDefQuery/testdata.js
  test/wallet-web/test/wallet/testdata.js
  test/wallet-web/test/wallet/walletCredentialQuery.spec.js
Labels: cla-signed, refactor

#699 fix: QueryByFrame to support undefined 'example'
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByFrame.js
  cmd/wallet-web/src/pages/chapi/wallet/get/multiQuery.js
Labels: cla-signed

#700 fix: use DID from credential subject ID to present
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByFrame.js
  cmd/wallet-web/src/pages/chapi/wallet/get/multiQuery.js
Labels: cla-signed

#702 fix: Fix the scrollbar issue on wallet cred dialog box.
  cmd/wallet-web/src/components/CredentialCards/JsonModal.vue
Labels: cla-signed

#703 feat: add support for pk creds generated by apple touch/face id
  pkg/restapi/device/appleattestation.go
  pkg/restapi/device/operations.go
  pkg/restapi/device/operations_test.go
Labels: cla-signed

#704 chore: update to the latest agent-sdk
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  go.mod
  go.sum
  pkg/restapi/internal/mocks/protocol/outofband.go
  test/bdd/go.sum
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#705 chore: update AFGO + agent-sdk
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/chapi/wallet/didcomm/blindedRouter.js
  go.mod
  go.sum
  test/bdd/fixtures/wallet-web/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
  test/wallet-web/test/mocks/adapters/issuerAdapter.js
Labels: chore, cla-signed

#707 chore: Update agent-sdk version
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#708 chore: update aries to 7ec3a2c4697c512726ffaa4143e56491405dd828
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  go.mod
  go.sum
  test/bdd/fixtures/wallet-web/.env
  test/bdd/go.mod
  test/bdd/go.sum
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed
