Repository trustbloc/wallet, pull requests merged in 2021-12, with the labels that each got.

#1271 feat: Link Vault with credential screen
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/Credentials.vue
  cmd/wallet-web/src/pages/Vaults.vue
Labels: type: enhancement, cla-signed, area: UI

#1274 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1276 feat: refresh vaults when the new one is created
  cmd/wallet-web/src/components/Modal/AddVault.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/Vaults.vue
Labels: type: enhancement, cla-signed, area: UI

#1267 refactor: refactored wallet-web folder structure
  cmd/wallet-web/src/components/CredentialDetails/Banner.vue
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
  cmd/wallet-web/src/components/DIDManagement/Preferences.vue
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/layouts/DashboardLayout.vue
  cmd/wallet-web/src/layouts/Get.vue
  cmd/wallet-web/src/layouts/WACI.vue
  cmd/wallet-web/src/pages/Credentials.vue
  cmd/wallet-web/src/pages/DIDConnect.vue
  cmd/wallet-web/src/pages/LoginHandle.vue
  cmd/wallet-web/src/pages/MultipleQuery.vue
  cmd/wallet-web/src/pages/NotFound.vue
  cmd/wallet-web/src/pages/PresentationDefQuery.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/src/pages/layout/DashboardContent.vue
  cmd/wallet-web/src/router/routes.js
  cmd/wallet-web/src/utils/mixins/common/helper.js
  cmd/wallet-web/src/utils/mixins/common/presentationDefSchema.js
  cmd/wallet-web/src/utils/mixins/common/presentationExchange.js
  cmd/wallet-web/src/utils/mixins/common/register.js
  cmd/wallet-web/src/utils/mixins/get/didConn.js
  cmd/wallet-web/src/utils/mixins/get/getCredentialsByQuery.js
  cmd/wallet-web/src/utils/mixins/handler/chapi.js
  cmd/wallet-web/src/utils/mixins/handler/waci.js
  cmd/wallet-web/src/utils/mixins/index.js
  cmd/wallet-web/test/specs/get.spec.js
  cmd/wallet-web/test/specs/presexch.spec.js
  cmd/wallet-web/test/specs/store.spec.js
Labels: cla-signed, type: refactor, area: UI

#1281 feat: dynamically update vault name in credentials screen
  cmd/wallet-web/src/components/Navbar/Navbar.vue
  cmd/wallet-web/src/components/Navbar/NavbarLink.vue
  cmd/wallet-web/src/pages/Credentials.vue
  cmd/wallet-web/src/translations/Credentials/en.json
  cmd/wallet-web/src/translations/Credentials/fr.json
Labels: type: enhancement, cla-signed, area: UI

#1285 feat: Refactor flyout menu , add vault flyout menus and move delete credential to teleport
  cmd/wallet-web/src/components/CredentialDetails/DeleteCredentialModal.vue
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenuButton.vue
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenuList.vue
  cmd/wallet-web/src/components/Modal/AddVault.vue
  cmd/wallet-web/src/components/Modal/Modal.vue
  cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/pages/Vaults.vue
  cmd/wallet-web/src/translations/Vaults/en.json
  cmd/wallet-web/src/translations/Vaults/fr.json
  test/ui-automation/test/helpers/wallet.js
Labels: type: enhancement, cla-signed, area: UI

#1291 fix: Adding id as prop to default and vault flyout menus
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
  cmd/wallet-web/src/pages/Credentials.vue
  cmd/wallet-web/src/pages/Vaults.vue
Labels: cla-signed

#1283 feat: display credentials per vaults in credentials screen
  cmd/wallet-web/scripts/setup_test.sh
  cmd/wallet-web/src/components/CredentialDetails/Banner.vue
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/pages/Credentials.vue
  cmd/wallet-web/src/store/modules/user.js
  scripts/wallet_web_dev_start.sh
  test/ui-automation/test/specs/credential-interaction-flow.js
Labels: type: enhancement, cla-signed, area: UI

#1293 refactor: onboard user flow to support updated KMS API
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  go.mod
  go.sum
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  pkg/restapi/oidc/signer.go
  scripts/generate_test_keys.sh
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
  test/fixtures/wallet-web/oathkeeper-config/auth-keyserver/config.yaml
  test/fixtures/wallet-web/oathkeeper-config/auth-keyserver/rules/resource-server.json
  test/fixtures/wallet-web/oathkeeper-config/ops-keyserver/config.yaml
  test/fixtures/wallet-web/oathkeeper-config/ops-keyserver/rules/resource-server.json
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
Labels: cla-signed

#1305 feat: added selected vault and credential ids to vuex store
  cmd/wallet-web/src/store/modules/user.js
Labels: type: enhancement, cla-signed, area: UI

#1300 feat: added vault filter flyout
  cmd/wallet-web/src/components/CredentialDetails/DeleteCredentialModal.vue
  cmd/wallet-web/src/components/Flyout/Flyout.vue
  cmd/wallet-web/src/components/Flyout/FlyoutButton.vue
  cmd/wallet-web/src/components/Flyout/FlyoutMenu.vue
  cmd/wallet-web/src/components/FlyoutMenu/FlyoutMenu.vue
  cmd/wallet-web/src/components/ToolTip/ToolTip.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/pages/Credentials.vue
  cmd/wallet-web/src/pages/Vaults.vue
  cmd/wallet-web/src/translations/Credentials/en.json
  cmd/wallet-web/src/translations/Credentials/fr.json
Labels: type: enhancement, cla-signed, area: UI, component: vault filter flyout

#1328 fix: updated tailwind imports in mock test pages
  test/mock/adapter/templates/css/tailwind.css
  test/mock/adapter/templates/webWallet.html
  test/mock/demo-login-consent-server/main.go
  test/mock/demo-login-consent-server/templates/bankconsent.html
  test/mock/demo-login-consent-server/templates/banklogin.html
  test/mock/demo-login-consent-server/templates/consent.html
  test/mock/demo-login-consent-server/templates/css/tailwind.css
  test/mock/demo-login-consent-server/templates/login.html
  test/mock/demo-login-consent-server/templates/uploadCred.html
  test/mock/demo-login-consent-server/templates/uploadCredConsent.html
Labels: cla-signed, type: fix, area: UI

#1330 feat: Enhance closing logic for the modal component
  cmd/wallet-web/src/components/Modal/Modal.vue
  cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
  cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/Vaults.vue
Labels: cla-signed

#1332 feat: sync vault filter selection with store, add extended link reusable component, refactor vault card
  cmd/wallet-web/src/components/AppLink/AppLink.vue
  cmd/wallet-web/src/components/Flyout/Flyout.vue
  cmd/wallet-web/src/components/Modal/Modal.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/Credentials.vue
  cmd/wallet-web/src/pages/Vaults.vue
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/src/store/modules/user.js
Labels: type: enhancement, cla-signed, area: UI

#1333 chore: added test for delete credential back
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/credential-interaction-flow.js
Labels: cla-signed, type: chore, area: integration tests

#1335 feat: added loading state, auto refresh to add and delete vault modals
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
  cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
Labels: type: enhancement, cla-signed, area: UI

#1337 feat: WACI issuance implementation
  cmd/wallet-web/package.json
  cmd/wallet-web/src/components/CredentialDetails/DeleteCredentialModal.vue
  cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
  cmd/wallet-web/src/layouts/WACI.vue
  cmd/wallet-web/src/pages/WACIIssue.vue
  cmd/wallet-web/src/translations/CHAPI/en.json
  cmd/wallet-web/src/translations/CHAPI/fr.json
  cmd/wallet-web/src/utils/mixins/handler/waci.js
Labels: cla-signed

#1342 feat: WACI issuance demo
  test/mock/adapter/adapter.go
  test/mock/adapter/didcomm.go
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
  test/mock/adapter/main.go
  test/mock/adapter/sampledata/credential_manifest.json
  test/mock/adapter/sampledata/fulfillment_dl_vp.json
  test/mock/adapter/sampledata/sample_udcvc.json
  test/mock/adapter/templates/issuer.html
  test/mock/adapter/verifier.go
Labels: cla-signed

#1353 fix: Incorrect UI alignment with Multiple OIDC providers
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
Labels: cla-signed

#1360 feat: Wallet UI tests for WACI Issuance
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/router/index.js
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/waci-issuance-flow.js
  test/ui-automation/test/specs/waci-share-flow.js
  test/ui-automation/wdio.conf.js
  test/ui-automation/wdio.shared.conf.js
Labels: cla-signed

#1370 fix: Update signinText and signuptext to logo Url in oidc config
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/oidc-config/demo_providers.yaml
  test/fixtures/wallet-web/static/images/demo_provider.svg
  test/fixtures/wallet-web/static/images/signin_logo.svg
  test/fixtures/wallet-web/static/images/signup_logo.svg
  test/ui-automation/test/helpers/wallet.js
Labels: cla-signed

#1374 feat: Support to set the order for odic providers
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
Labels: cla-signed

#1375 feat: input field validation for add vault modal
  cmd/wallet-web/src/assets/img/icons-checkmark.svg
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
  cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
  cmd/wallet-web/src/components/Vaults/RenameVaultModal.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/Vaults.vue
  cmd/wallet-web/src/translations/Vaults/en.json
  cmd/wallet-web/src/translations/Vaults/fr.json
  cmd/wallet-web/tailwind.js
Labels: type: enhancement, cla-signed, area: UI

#1371 feat: WACI issuance test - user not signed in
  test/mock/adapter/adapter.go
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/credential-interaction-flow.js
  test/ui-automation/test/specs/waci-issuance-flow.js
Labels: cla-signed

#1378 fix: Loading spinner is not centered in the authentication providers
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
Labels: cla-signed

#1381 chore: hub-auth docker update
  test/fixtures/wallet-web/.env
Labels: cla-signed

#1380 feat: added validation against existing vaults names
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/Vaults.vue
Labels: type: enhancement, cla-signed, area: UI

#1386 feat: Disable delete for the last vault and fix rename modal bug
  cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
  cmd/wallet-web/src/components/Vaults/RenameVaultModal.vue
  cmd/wallet-web/src/pages/Vaults.vue
Labels: cla-signed

#1385 feat: updated WACI Share UI to the new designs
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/layouts/WACI.vue
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/src/router/routes.js
  cmd/wallet-web/src/translations/CHAPI/en.json
  cmd/wallet-web/src/translations/CHAPI/fr.json
  cmd/wallet-web/tailwind.js
Labels: type: enhancement, cla-signed, area: UI
