Repository trustbloc/wallet, pull requests merged in 2021-06, with the labels that each got.

#746 chore: update to agent-sdk with enabled remote context fetching
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
Labels: cla-signed

#751 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/DIDManagement.vue
  cmd/wallet-web/src/pages/chapi/wallet/didmgmt/didManager.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
  test/wallet-web/test/mocks/adapters/issuerAdapter.js
Labels: cla-signed

#749 feat: Update stored credential layout in the dashboard
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/Layout/DashboardLayout.vue
  cmd/wallet-web/src/pages/WebWallet.vue
Labels: cla-signed

#755 fix: adjusted container alignment
  cmd/wallet-web/src/pages/chapi/Login.vue
Labels: cla-signed

#756 feat: Move the DID Mangement under settings
  cmd/wallet-web/src/assets/img/settings.png
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/Layout/DashboardLayout.vue
  cmd/wallet-web/src/pages/Layout/TopNavbar.vue
  cmd/wallet-web/src/pages/chapi/Settings.vue
Labels: cla-signed

#759 fix: added logout button, fixed sidebar width
  cmd/wallet-web/src/assets/scss/md/_inputs.scss
  cmd/wallet-web/src/assets/scss/md/_sidebar-and-main-panel.scss
  cmd/wallet-web/src/components/SidebarPlugin/SideBar.vue
  cmd/wallet-web/src/pages/Layout/DashboardLayout.vue
  cmd/wallet-web/src/pages/chapi/Logout.vue
Labels: cla-signed

#760 chore: Update package lock json file
  cmd/wallet-web/package-lock.json
Labels: cla-signed

#761 chore: Update to npm 7 and recent agent-sdk-web version
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  docs/test/test.md
Labels: cla-signed

#763 chore: upgrade tailwindcss to 2.1.4
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/assets/scss/md/_navbars.scss
  cmd/wallet-web/src/assets/scss/md/_sidebar-and-main-panel.scss
  cmd/wallet-web/src/components/SidebarPlugin/SideBar.vue
  cmd/wallet-web/src/pages/Layout/DashboardLayout.vue
  cmd/wallet-web/src/pages/chapi/Logout.vue
  cmd/wallet-web/tailwind.js
  test/bdd/mock/demo-login-consent-server/templates/banklogin.html
  test/bdd/mock/demo-login-consent-server/templates/login.html
  test/bdd/mock/demo-login-consent-server/templates/uploadCred.html
Labels: cla-signed, dependencies

#765 chore: Specify lockfile version
  package-lock.json
  test/wallet-web/package-lock.json
Labels: cla-signed

#771 feat: Fetch the list of providers from Hub Auth and render on sign up page
  cmd/wallet-web/src/pages/chapi/Signup.vue
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/modules/options.js
  images/wallet-web/templates/default.conf.template
  test/bdd/fixtures/wallet-web/docker-compose-web.yml
Labels: cla-signed

#770 feat: added config file for Dependabot
  .github/dependabot.yml
Labels: cla-signed, enhancement

#769 fix: fixed chapi components layout
  cmd/wallet-web/src/pages/chapi/DIDAuth.vue
  cmd/wallet-web/src/pages/chapi/DIDConnect.vue
  cmd/wallet-web/src/pages/chapi/GetCredentials.vue
  cmd/wallet-web/src/pages/chapi/MultipleQuery.vue
  cmd/wallet-web/src/pages/chapi/PresentationDefQuery.vue
  cmd/wallet-web/src/pages/chapi/QueryByFrame.vue
  cmd/wallet-web/src/pages/chapi/Store.vue
  cmd/wallet-web/src/pages/webWalletSamples.js
Labels: cla-signed

#779 feat: added test package.json to Dependabot config
  .github/dependabot.yml
Labels: cla-signed, enhancement

#782 feat: added brand colors to tailwind theme
  cmd/wallet-web/tailwind.js
Labels: cla-signed, enhancement

#783 feat: added brand gradients to tailwind theme
  cmd/wallet-web/tailwind.js
Labels: cla-signed, enhancement

#786 fix: Hydra login challenge cookie missing issue
  cmd/wallet-web/src/pages/chapi/Signup.vue
  pkg/restapi/common/oidc/api.go
  pkg/restapi/common/oidc/client.go
  pkg/restapi/common/oidc/mock.go
  pkg/restapi/oidc/operations.go
Labels: cla-signed

#787 chore: Update latest hub-auth
  test/bdd/fixtures/wallet-web/.env
Labels: cla-signed

#791 feat: Implement background of the sign-in page and common layout using TrustBloc theme.
  .gitattributes
  cmd/wallet-web/src/assets/img/onboarding-bg-lg.svg
  cmd/wallet-web/src/assets/img/onboarding-flare-lg.png
  cmd/wallet-web/src/pages/chapi/Signup.vue
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#795 feat: added configuration for system spacing in theme
  cmd/wallet-web/tailwind.js
Labels: cla-signed, enhancement

#797 feat: Add list icons and signup buttons using trustbloc margin theme.
  cmd/wallet-web/src/assets/img/onboarding-icon-1.svg
  cmd/wallet-web/src/assets/img/onboarding-icon-2.svg
  cmd/wallet-web/src/assets/img/onboarding-icon-3.svg
  cmd/wallet-web/src/pages/chapi/Signup.vue
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#798 feat: added font family, sizes, line heights, heading styles to theme
  cmd/wallet-web/src/App.vue
  cmd/wallet-web/tailwind.js
Labels: cla-signed, enhancement
