Repository trustbloc/wallet, pull requests merged in 2021-07, with the labels that each got.

#799 feat: Add common footer to trustbloc page
  cmd/wallet-web/src/pages/Layout/ContentFooter.vue
  cmd/wallet-web/src/pages/chapi/Signup.vue
  cmd/wallet-web/src/pages/layout/Content.vue
  cmd/wallet-web/src/pages/layout/ContentFooter.vue
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/src/pages/layout/MobileMenu.vue
  cmd/wallet-web/src/pages/layout/TopNavbar.vue
  cmd/wallet-web/src/router/index.js
Labels: cla-signed

#803 fix: Update Trustbloc logo
  cmd/wallet-web/src/assets/img/logo.png
  cmd/wallet-web/src/assets/img/logo.svg
  cmd/wallet-web/src/components/SidebarPlugin/SideBar.vue
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/pages/chapi/Signup.vue
Labels: cla-signed

#802 feat: Add dynamic footer year and reshuffle footer alignment for mobile screen as per UX design
  cmd/wallet-web/src/pages/chapi/Signup.vue
  cmd/wallet-web/src/pages/layout/ContentFooter.vue
Labels: cla-signed

#804 feat: added common styles for buttons
  cmd/wallet-web/tailwind.js
Labels: cla-signed, enhancement

#806 feat: Remove beat loader and add demo-provider icon and updated ui
  cmd/wallet-web/src/assets/img/demo_provider.svg
  cmd/wallet-web/src/pages/chapi/Signup.vue
Labels: cla-signed

#818 fix: changed footer id to a non-reserved value
  cmd/wallet-web/src/pages/layout/ContentFooter.vue
Labels: cla-signed

#824 chore: Update edge-agent with latest hub-auth changes
  cmd/wallet-web/src/pages/chapi/Signup.vue
  test/bdd/fixtures/wallet-web/.env
  test/bdd/fixtures/wallet-web/docker-compose-server.yml
  test/bdd/fixtures/wallet-web/oidc-config/bdd_providers.yaml
  test/bdd/fixtures/wallet-web/oidc-config/demo_providers.yaml
  test/bdd/fixtures/wallet-web/static/images/demo_provider.svg
Labels: cla-signed

#815 feat: created reusable styled component for input fields
  cmd/wallet-web/src/assets/img/danger-icon.svg
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/src/pages/chapi/Signup.vue
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#826 fix: adjusted the fader
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/tailwind.js
Labels: cla-signed

#822 feat: webwallet migration to universal wallet
  Makefile
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/pages/DIDManagement.vue
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/TablePresentation.vue
  cmd/wallet-web/src/pages/WebWallet.vue
  cmd/wallet-web/src/pages/chapi/DIDAuth.vue
  cmd/wallet-web/src/pages/chapi/DIDConnect.vue
  cmd/wallet-web/src/pages/chapi/Get.vue
  cmd/wallet-web/src/pages/chapi/GetCredentials.vue
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/pages/chapi/Logout.vue
  cmd/wallet-web/src/pages/chapi/MultipleQuery.vue
  cmd/wallet-web/src/pages/chapi/PresentationDefQuery.vue
  cmd/wallet-web/src/pages/chapi/QueryByFrame.vue
  cmd/wallet-web/src/pages/chapi/RegisterDevice.vue
  cmd/wallet-web/src/pages/chapi/Signup.vue
  cmd/wallet-web/src/pages/chapi/Store.vue
  cmd/wallet-web/src/pages/chapi/wallet/common/didExchange.js
  cmd/wallet-web/src/pages/chapi/wallet/common/helper.js
  cmd/wallet-web/src/pages/chapi/wallet/common/keyValStore.js
  cmd/wallet-web/src/pages/chapi/wallet/common/presentationExchange.js
  cmd/wallet-web/src/pages/chapi/wallet/common/register.js
  cmd/wallet-web/src/pages/chapi/wallet/common/util.js
  cmd/wallet-web/src/pages/chapi/wallet/device/login.js
  cmd/wallet-web/src/pages/chapi/wallet/device/register.js
  cmd/wallet-web/src/pages/chapi/wallet/didcomm/blindedRouter.js
  cmd/wallet-web/src/pages/chapi/wallet/didcomm/mediator.js
  cmd/wallet-web/src/pages/chapi/wallet/didmgmt/didManager.js
  cmd/wallet-web/src/pages/chapi/wallet/get/didAuth.js
  cmd/wallet-web/src/pages/chapi/wallet/get/didConn.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentials.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByFrame.js
  cmd/wallet-web/src/pages/chapi/wallet/get/getCredentialsByQuery.js
  cmd/wallet-web/src/pages/chapi/wallet/get/multiQuery.js
  cmd/wallet-web/src/pages/chapi/wallet/handler/chapi.js
  cmd/wallet-web/src/pages/chapi/wallet/index.js
  cmd/wallet-web/src/pages/chapi/wallet/register/register.js
  cmd/wallet-web/src/pages/chapi/wallet/register/walletManager.js
  cmd/wallet-web/src/pages/chapi/wallet/store/saveCredential.js
  cmd/wallet-web/src/pages/webWalletSamples.js
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/modules/connections.js
  cmd/wallet-web/src/store/modules/credentials.js
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/src/store/modules/user.js
  cmd/wallet-web/vue.config.js
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
Labels: cla-signed

#828 feat: added logic for configurable assets
  cmd/wallet-web/src/components/SidebarPlugin/SideBar.vue
  cmd/wallet-web/src/pages/chapi/Login.vue
  cmd/wallet-web/src/pages/chapi/Signup.vue
  cmd/wallet-web/src/store/modules/options.js
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  test/bdd/fixtures/wallet-web/docker-compose-web.yml
Labels: cla-signed, enhancement

#836 fix: added missing closing tags
  cmd/wallet-web/src/pages/chapi/Signup.vue
Labels: cla-signed

#837 feat: refactoring wallet vue application structure
  cmd/wallet-web/src/components/CredentialCards/JsonModal.vue
  cmd/wallet-web/src/pages/BlockNoAuth.vue
  cmd/wallet-web/src/pages/DIDAuth.vue
  cmd/wallet-web/src/pages/DIDConnect.vue
  cmd/wallet-web/src/pages/DIDManagement.vue
  cmd/wallet-web/src/pages/Dashboard.vue
  cmd/wallet-web/src/pages/Get.vue
  cmd/wallet-web/src/pages/Governance.vue
  cmd/wallet-web/src/pages/Login.vue
  cmd/wallet-web/src/pages/Logout.vue
  cmd/wallet-web/src/pages/MultipleQuery.vue
  cmd/wallet-web/src/pages/PresentationDefQuery.vue
  cmd/wallet-web/src/pages/RegisterDevice.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/src/pages/Worker.vue
  cmd/wallet-web/src/pages/demos/Connections.vue
  cmd/wallet-web/src/pages/demos/IssueCredential.vue
  cmd/wallet-web/src/pages/demos/PresentProof.vue
  cmd/wallet-web/src/pages/demos/Relationships.vue
  cmd/wallet-web/src/pages/demos/WebWallet.vue
  cmd/wallet-web/src/pages/demos/webWalletSamples.js
  cmd/wallet-web/src/pages/layout/DashboardLayout.vue
  cmd/wallet-web/src/pages/mixins/common/helper.js
  cmd/wallet-web/src/pages/mixins/common/presentationDefSchema.js
  cmd/wallet-web/src/pages/mixins/common/presentationExchange.js
  cmd/wallet-web/src/pages/mixins/common/register.js
  cmd/wallet-web/src/pages/mixins/get/didConn.js
  cmd/wallet-web/src/pages/mixins/get/getCredentialsByQuery.js
  cmd/wallet-web/src/pages/mixins/handler/chapi.js
  cmd/wallet-web/src/pages/mixins/index.js
  cmd/wallet-web/src/router/index.js
Labels: cla-signed

#832 feat: Launch the login page as a pop up window and redirect to signup after successful signup
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/pages/Logout.vue
  cmd/wallet-web/src/pages/Signup.vue
  test/bdd/features/login.feature
  test/bdd/features/signup.feature
  test/bdd/pkg/login/steps.go
Labels: cla-signed

#842 ci: Switch to GitHub actions
  .github/workflows/ci.yml
  ci/azp-dependencies.yml
  test/bdd/fixtures/wallet-web/docker-compose-web.yml
Labels: cla-signed

#843 ci: Add npm login details in publish job
  .github/workflows/ci.yml
Labels: cla-signed

#845 ci: GitHub publish job
  .github/workflows/build.yml
  .github/workflows/publish.yml
  README.md
  ci/version_var.sh
Labels: cla-signed

#841 feat: Login updated UX
  test/bdd/mock/demo-login-consent-server/templates/login.html
Labels: cla-signed

#846 ci: publish job - build wallet web
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: cla-signed

#847 feat: enhancement in wallet preference updates
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/DIDManagement.vue
  cmd/wallet-web/src/pages/mixins/common/helper.js
Labels: cla-signed

#848 test: remove unused container
  test/bdd/fixtures/wallet-web/docker-compose-web.yml
Labels: cla-signed

#850 chore: update docker manifest with new repo name
  images/wallet-server/Dockerfile
  images/wallet-web/Dockerfile
Labels: cla-signed

#851 ci: log versions in publish job
  .github/workflows/build.yml
Labels: cla-signed

#853 fix: incorrect generated docker image prefix
  .github/workflows/build.yml
Labels: cla-signed

#855 feat: created reusable logo component
  cmd/wallet-web/src/assets/img/logo.svg
  cmd/wallet-web/src/components/Logo/Logo.vue
  cmd/wallet-web/src/components/SidebarPlugin/SideBar.vue
  cmd/wallet-web/src/pages/Login.vue
  cmd/wallet-web/src/pages/Signup.vue
Labels: cla-signed, enhancement

#856 ci: publish - set lfs to true
  .github/workflows/build.yml
Labels: cla-signed

#860 fix: Login flow showing blank screen
  cmd/wallet-web/src/main.js
Labels: cla-signed

#862 chore: removed image containing old logo
  cmd/wallet-web/src/assets/img/home_wallet.png
  cmd/wallet-web/src/pages/Login.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/tailwind.js
Labels: cla-signed, refactor

#863 docs: webwallet doc updates
  docs/components/web_wallet.md
Labels: cla-signed

#864 docs: updated webwallet docs
  docs/components/web_wallet.md
Labels: cla-signed

#865 docs: fix invitation samples
  docs/components/web_wallet.md
Labels: cla-signed

#867 fix: Temporary removing popup window to unblock sandbox
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/pages/Signup.vue
Labels: cla-signed

#868 fix: sign-up remove window open line
  cmd/wallet-web/src/pages/Signup.vue
Labels: cla-signed

#866 feat: added initial configuration for i18n
  cmd/wallet-web/.env
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/public/index.html
  cmd/wallet-web/src/App.vue
  cmd/wallet-web/src/i18n.js
  cmd/wallet-web/src/locales/en.json
  cmd/wallet-web/src/locales/fr.json
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/layout/ContentFooter.vue
  cmd/wallet-web/src/utils/i18n/document.js
  cmd/wallet-web/vue.config.js
Labels: cla-signed, enhancement

#871 feat: TrustBloc DID to Orb DID
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/DIDManagement.vue
  cmd/wallet-web/src/pages/Login.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/mixins/common/register.js
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed

#874 chore: refactored hrefs to lowercase, added missing changes
  cmd/wallet-web/src/pages/DIDManagement.vue
  cmd/wallet-web/src/pages/Login.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
Labels: cla-signed, refactor

#876 chore: removed parse-duration from /cmd/wallet-web/
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: chore, cla-signed

#881 feat: wallet UI tests
  Makefile
  cmd/wallet-web/.babelrc
  cmd/wallet-web/.gitignore
  cmd/wallet-web/alias.config.js
  cmd/wallet-web/karma.conf.js
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/scripts/generate_test_keys.sh
  cmd/wallet-web/scripts/setup_test.sh
  cmd/wallet-web/test/common.js
  cmd/wallet-web/test/fixtures/.env
  cmd/wallet-web/test/fixtures/agent-config.json
  cmd/wallet-web/test/fixtures/docker-compose.yml
  cmd/wallet-web/test/fixtures/testdata/prc-vc.json
  cmd/wallet-web/test/fixtures/testdata/sample-presentation-1.json
  cmd/wallet-web/test/fixtures/testdata/sample-presentation-2.json
  cmd/wallet-web/test/fixtures/testdata/udc-bbs-vc.json
  cmd/wallet-web/test/fixtures/testdata/udc-vc.json
  cmd/wallet-web/test/specs/get.spec.js
  cmd/wallet-web/test/specs/store.spec.js
  cmd/wallet-web/vue.config.js
  cmd/wallet-web/webpack.test.js
Labels: cla-signed

#882 feat: Updated pop up window design using vuex
  cmd/wallet-server/startcmd/start.go
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/LoginHandle.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/index.js
  cmd/wallet-web/src/store/modules/user.js
  test/bdd/mock/demo-login-consent-server/main.go
Labels: cla-signed

#883 fix: Address pop up watch window comment.
  cmd/wallet-web/src/pages/Signup.vue
Labels: cla-signed

#885 test: ui automation setup
  .github/workflows/build.yml
  Makefile
  scripts/check_js_integration.sh
  scripts/check_wallet_server_integration.sh
  scripts/run_ui_automation.sh
  test/ui-automation/.gitignore
  test/ui-automation/package-lock.json
  test/ui-automation/package.json
  test/ui-automation/test/helpers/chapi.js
  test/ui-automation/test/helpers/constants.js
  test/ui-automation/test/helpers/index.js
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/signup.js
  test/ui-automation/wdio.conf.js
  test/ui-automation/wdio.shared.conf.js
  test/wallet-web/.babelrc
  test/wallet-web/.npmrc
  test/wallet-web/karma.conf.js
  test/wallet-web/package-lock.json
  test/wallet-web/package.json
  test/wallet-web/scripts/setup_assets.sh
  test/wallet-web/test/common.js
  test/wallet-web/test/jsonld_contexts.js
  test/wallet-web/test/mocks/adapters/issuerAdapter.js
  test/wallet-web/test/mocks/index.js
  test/wallet-web/test/presentationDefQuery/presentationDef.spec.js
  test/wallet-web/test/presentationDefQuery/testdata.js
  test/wallet-web/test/wallet/testdata.js
  test/wallet-web/test/wallet/walletCredentialQuery.blinded.spec.js
  test/wallet-web/test/wallet/walletCredentialQuery.spec.js
  test/wallet-web/test/wallet/walletStore.spec.js
  test/wallet-web/webpack.config.js
Labels: cla-signed

#887 feat: login enhancements
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/store/modules/options.js
Labels: cla-signed

#888 chore: enable wallet web unit test in CI
  .github/workflows/build.yml
  cmd/wallet-web/alias.config.js
  cmd/wallet-web/karma.conf.js
  cmd/wallet-web/test/common.js
  cmd/wallet-web/test/fixtures/agent-config.json
  cmd/wallet-web/test/fixtures/docker-compose.yml
  cmd/wallet-web/test/fixtures/testdata/prc-vc.json
  cmd/wallet-web/test/fixtures/testdata/sample-presentation-1.json
  cmd/wallet-web/test/fixtures/testdata/sample-presentation-2.json
  cmd/wallet-web/test/fixtures/testdata/udc-bbs-vc.json
  cmd/wallet-web/test/fixtures/testdata/udc-vc.json
  cmd/wallet-web/test/specs/get.spec.js
  cmd/wallet-web/test/specs/store.spec.js
  cmd/wallet-web/vue.config.js
  cmd/wallet-web/webpack.test.js
Labels: cla-signed

#890 test: rename docker containers and urls
  .github/workflows/build.yml
  cmd/wallet-web/scripts/generate_test_keys.sh
  cmd/wallet-web/test/fixtures/.env
  cmd/wallet-web/test/fixtures/docker-compose.yml
  docs/components/web_wallet.md
  docs/test/test.md
  pkg/restapi/oidc/operations_test.go
  scripts/generate_test_keys.sh
  scripts/run_ui_automation.sh
  test/fixtures/edv-oathkeeper/config.yaml
  test/fixtures/edv-oathkeeper/rules/resource-server.json
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
  test/fixtures/wallet-web/docker-compose-web.yml
  test/fixtures/wallet-web/hydra-config/auth-rest-hydra_configure.sh
  test/fixtures/wallet-web/hydra-config/bdd_auth-rest-hydra_configure.sh
  test/fixtures/wallet-web/hydra-config/bdd_hydra_configure.sh
  test/fixtures/wallet-web/hydra-config/demo_hydra_configure.sh
  test/fixtures/wallet-web/mysql-config/mysql_config.sql
  test/fixtures/wallet-web/oathkeeper-config/auth-keyserver/config.yaml
  test/fixtures/wallet-web/oathkeeper-config/auth-keyserver/rules/resource-server.json
  test/fixtures/wallet-web/oathkeeper-config/bdd-auth-keyserver/config.yaml
  test/fixtures/wallet-web/oathkeeper-config/demo-auth-keyserver/rules/resource-server.json
  test/fixtures/wallet-web/oathkeeper-config/demo-ops-keyserver/config.yaml
  test/fixtures/wallet-web/oathkeeper-config/demo-ops-keyserver/rules/resource-server.json
  test/fixtures/wallet-web/oathkeeper-config/ops-keyserver/config.yaml
  test/fixtures/wallet-web/oathkeeper-config/ops-keyserver/rules/resource-server.json
  test/fixtures/wallet-web/oidc-config/bdd_providers.yaml
  test/fixtures/wallet-web/oidc-config/demo_providers.yaml
  test/ui-automation/wdio.conf.js
Labels: cla-signed

#891 docs: Update readme file
  README.md
  docs/components/user_agent_wasm.md
  docs/components/wallet_server.md
  docs/components/wallet_web.md
Labels: cla-signed
