Repository trustbloc/wallet, pull requests merged in 2022-05, with the labels that each got.

#1656 chore: WACI issuance automation - dynamic test data
  test/mock/adapter/adapter.go
  test/mock/adapter/sampledata/sample_prc_fulfillment.json
  test/mock/adapter/sampledata/sample_prc_fulfillment_unsigned.json
  test/mock/adapter/templates/issuer/waci-issuer.html
Labels: cla-signed

#1657 feat: implemented 404 page, other enhancements
  .husky/post-checkout
  .husky/post-commit
  .husky/post-merge
  .husky/pre-push
  cmd/wallet-web/src/App.vue
  cmd/wallet-web/src/assets/img/Icons-sm--close-icon.svg
  cmd/wallet-web/src/assets/img/close-icon.svg
  cmd/wallet-web/src/assets/img/close.svg
  cmd/wallet-web/src/assets/img/credential--arrow-right-icon-light.svg
  cmd/wallet-web/src/assets/img/credential--arrow-right-icon.svg
  cmd/wallet-web/src/assets/img/credential--generic-icon.svg
  cmd/wallet-web/src/assets/img/credentials.svg
  cmd/wallet-web/src/assets/img/danger-icon.svg
  cmd/wallet-web/src/assets/img/demo_provider.svg
  cmd/wallet-web/src/assets/img/icons-checkmark.svg
  cmd/wallet-web/src/assets/img/icons-md--credentials-icon.svg
  cmd/wallet-web/src/assets/img/icons-sm--chevron-down-icon.svg
  cmd/wallet-web/src/assets/img/icons-sm--plus-icon.svg
  cmd/wallet-web/src/assets/img/icons-sm--vault-icon.svg
  cmd/wallet-web/src/assets/img/logo.svg
  cmd/wallet-web/src/assets/img/menu-icon.svg
  cmd/wallet-web/src/assets/img/onboarding-bg-lg.svg
  cmd/wallet-web/src/assets/img/onboarding-bg-sm.svg
  cmd/wallet-web/src/assets/img/onboarding-icon-1.svg
  cmd/wallet-web/src/assets/img/onboarding-icon-2.svg
  cmd/wallet-web/src/assets/img/onboarding-icon-3.svg
  cmd/wallet-web/src/assets/img/profile.svg
  cmd/wallet-web/src/assets/img/settings.svg
  cmd/wallet-web/src/assets/img/share.svg
  cmd/wallet-web/src/assets/img/signout.svg
  cmd/wallet-web/src/assets/img/small-lock-icon.svg
  cmd/wallet-web/src/assets/img/triangle-exclamation.svg
  cmd/wallet-web/src/assets/img/vaults.svg
  cmd/wallet-web/src/components/DIDManagement/CreateOrb.vue
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/components/Logo/Logo.vue
  cmd/wallet-web/src/components/WACI/WACILoading.vue
  cmd/wallet-web/src/components/WACI/WACISharing.vue
  cmd/wallet-web/src/components/icons/IconError.vue
  cmd/wallet-web/src/components/icons/IconSpinner.vue
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/pages/DIDAuth.vue
  cmd/wallet-web/src/pages/DIDConnect.vue
  cmd/wallet-web/src/pages/MultipleQuery.vue
  cmd/wallet-web/src/pages/NotFound.vue
  cmd/wallet-web/src/pages/PresentationDefQuery.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/router/routes.js
Labels: type: enhancement, cla-signed, type: fix, area: UI

#1659 feat: updated to latest auth, refactored required code
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/layouts/Get.vue
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/pages/LoginHandle.vue
  cmd/wallet-web/src/pages/ProviderPopup.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/src/pages/Worker.vue
  cmd/wallet-web/src/router/routes.js
  cmd/wallet-web/test/specs/get.spec.js
  cmd/wallet-web/test/specs/store.spec.js
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/oidc-config/demo_providers.yaml
  test/fixtures/wallet-web/static/images/sign-in-icon-en.svg
  test/fixtures/wallet-web/static/images/sign-in-icon-fr.svg
  test/fixtures/wallet-web/static/images/sign-up-icon-en.svg
  test/fixtures/wallet-web/static/images/sign-up-icon-fr.svg
  test/fixtures/wallet-web/static/images/signin_logo.svg
  test/fixtures/wallet-web/static/images/signup_logo.svg
  test/ui-automation/package-lock.json
  test/ui-automation/package.json
Labels: cla-signed, type: refactor, area: UI

#1663 refactor: enabled automatic rebasing for dependabot PRs
  .github/dependabot.yml
Labels: cla-signed, type: refactor, area: UI

#1670 fix: rename Vue components to have multi-worded names
  cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoaderComponent.vue
Labels: cla-signed, type: refactor, area: UI

#1671 fix: apply dynamic focus styles to credential previews
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreviewComponent.vue
Labels: type: enhancement, cla-signed, area: UI

#1673 ci: semantic pull request (conventional commit) check
  .github/workflows/build.yml
Labels: cla-signed

#1674 ci: add pr condition for semantic pr check
  .github/workflows/build.yml
Labels: cla-signed

#1684 refactor: refactored PresentationDefQueryPage -> CHAPISharePage
  cmd/wallet-web/src/layouts/GetLayout.vue
  cmd/wallet-web/src/pages/CHAPISharePage.vue
Labels: cla-signed, type: refactor, area: UI

#1683 fix: [oidc4vci] web wallet view - fix OIDC router
  cmd/wallet-web/src/layouts/OIDCInitiateLayout.vue
  cmd/wallet-web/src/layouts/OIDCLayout.vue
  cmd/wallet-web/src/pages/OIDCSavePage.vue
Labels: cla-signed
