Repository trustbloc/wallet, pull requests merged in 2022-01, with the labels that each got.

#1394 feat: Add Automation test for Add Vault
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/src/pages/Vaults.vue
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/vault-interaction-flow.js
Labels: cla-signed

#1395 test: Add Vault Automation test
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/Vaults.vue
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/vault-interaction-flow.js
  test/ui-automation/wdio.shared.conf.js
Labels: cla-signed

#1397 docs: updated wallet documentation
  Makefile
  README.md
  docs/build.md
  docs/components/wallet_web.md
  docs/dev/dev-mode.md
  docs/test/test.md
Labels: area: documentation, type: enhancement, cla-signed

#1405 test: Add support for locale and Spacing scenarios
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/Vaults.vue
  cmd/wallet-web/src/translations/Vaults/fr.json
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/vault-interaction-flow.js
  test/ui-automation/wdio.conf.js
Labels: cla-signed

#1407 chore: hub-auth update
  test/fixtures/wallet-web/.env
Labels: cla-signed

#1409 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1411 chore: update edge-core
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  go.mod
  go.sum
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
  test/mock/demo-login-consent-server/go.mod
  test/mock/demo-login-consent-server/go.sum
Labels: cla-signed

#1412 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1414 fix: fixed error handling for missing credentials, i18n pluralization
  cmd/wallet-web/src/pages/WACIShare.vue
Labels: type: fix, area: UI

#1415 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1417 feat: added success screen for WACI Share flow
  cmd/wallet-web/src/assets/img/icons-circle-check.svg
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/src/translations/WACI/en.json
  cmd/wallet-web/src/translations/WACI/fr.json
  cmd/wallet-web/src/translations/en.js
  cmd/wallet-web/src/translations/fr.js
  test/ui-automation/test/specs/waci-share-flow.js
Labels: type: enhancement, cla-signed, area: UI

#1420 fix: added missing translation, cleaned up
  cmd/wallet-web/src/components/WACI/CredentialOverview.vue
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/src/translations/WACI/en.json
  cmd/wallet-web/src/translations/WACI/fr.json
Labels: type: enhancement, area: UI

#1419 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/fixtures/wallet-web/static/contexts/ld-contexts.json
  test/mock/adapter/adapter.go
  test/mock/adapter/sampledata/sample_udc_fulfillment.json
  test/mock/adapter/sampledata/sample_udcvc.json
Labels: cla-signed

#1425 chore: (#1278) Removing utils folder
  cmd/wallet-web/src/components/CredentialDetails/Banner.vue
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
  cmd/wallet-web/src/components/DIDManagement/Preferences.vue
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/components/WACI/CredentialBanner.vue
  cmd/wallet-web/src/components/WACI/CredentialOverview.vue
  cmd/wallet-web/src/layouts/Get.vue
  cmd/wallet-web/src/layouts/WACI.vue
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/mixins/common/helper.js
  cmd/wallet-web/src/mixins/common/presentationDefSchema.js
  cmd/wallet-web/src/mixins/common/presentationExchange.js
  cmd/wallet-web/src/mixins/common/register.js
  cmd/wallet-web/src/mixins/get/didConn.js
  cmd/wallet-web/src/mixins/get/getCredentialsByQuery.js
  cmd/wallet-web/src/mixins/handler/chapi.js
  cmd/wallet-web/src/mixins/handler/waci.js
  cmd/wallet-web/src/mixins/i18n/document.js
  cmd/wallet-web/src/mixins/i18n/getBrowserLocale.js
  cmd/wallet-web/src/mixins/i18n/getStartingLocale.js
  cmd/wallet-web/src/mixins/index.js
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/pages/Credentials.vue
  cmd/wallet-web/src/pages/DIDConnect.vue
  cmd/wallet-web/src/pages/MultipleQuery.vue
  cmd/wallet-web/src/pages/PresentationDefQuery.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/src/pages/WACIIssue.vue
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/src/plugins/i18n.js
  cmd/wallet-web/test/specs/presexch.spec.js
Labels: cla-signed

#1427 feat: updated WACI Issue UI
  cmd/wallet-web/src/components/WACI/CredentialDetailsTable.vue
  cmd/wallet-web/src/components/WACI/CredentialOverview.vue
  cmd/wallet-web/src/components/WACI/WACIActionButtonsContainer.vue
  cmd/wallet-web/src/components/WACI/WACICredentialsMissing.vue
  cmd/wallet-web/src/components/WACI/WACIError.vue
  cmd/wallet-web/src/components/WACI/WACILoading.vue
  cmd/wallet-web/src/components/WACI/WACISharing.vue
  cmd/wallet-web/src/components/WACI/WACISuccess.vue
  cmd/wallet-web/src/layouts/WACI.vue
  cmd/wallet-web/src/pages/WACIIssue.vue
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/src/translations/WACI/en.json
  cmd/wallet-web/src/translations/WACI/fr.json
  test/ui-automation/test/specs/waci-issuance-flow.js
Labels: type: enhancement, cla-signed, area: UI

#1432 chore: updated to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed, type: chore, dependencies

#1434 fix: fixed an issue waci issuance flow
  cmd/wallet-web/src/pages/WACIIssue.vue
Labels: cla-signed, type: fix, area: UI

#1440 fix: adjusted chapi automation test
  test/ui-automation/test/helpers/chapi.js
Labels: cla-signed, type: fix, area: integration tests

#1442 feat: implemented welcome message banner
  cmd/wallet-web/src/assets/img/credential-icon-colored.svg
  cmd/wallet-web/src/assets/img/vault-icon-colored.svg
  cmd/wallet-web/src/components/Vaults/WelcomeBanner.vue
  cmd/wallet-web/src/pages/Credentials.vue
  cmd/wallet-web/src/pages/Vaults.vue
  cmd/wallet-web/src/translations/Vaults/en.json
  cmd/wallet-web/src/translations/Vaults/fr.json
Labels: type: enhancement, cla-signed, area: UI

#1447 chore: hub-auth docker update
  test/fixtures/wallet-web/.env
Labels: cla-signed

#1452 chore: golang v1.17 update
  .github/workflows/build.yml
  .github/workflows/publish.yml
  Makefile
  cmd/wallet-server/go.mod
  go.mod
  test/mock/adapter/go.mod
  test/mock/demo-login-consent-server/go.mod
Labels: cla-signed

#1457 chore: upgraded alpine version to 3.15 in publish jobs
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: cla-signed, type: chore, dependencies

#1456 feat: added link to vaults in navbar logo
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/components/Logo/Logo.vue
  cmd/wallet-web/src/components/Navbar/Navbar.vue
Labels: type: enhancement, cla-signed, area: UI

#1465 chore: Agent SDK update
  cmd/wallet-web/package.json
  package-lock.json
Labels: cla-signed

#1468 chore: update latest afgo and agent-sdk
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/components/Navbar/Navbar.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/components/Vaults/WelcomeBanner.vue
  cmd/wallet-web/src/components/WACI/CredentialDetailsTable.vue
  cmd/wallet-web/src/layouts/WACI.vue
  cmd/wallet-web/src/pages/Signin.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/Vaults.vue
  cmd/wallet-web/src/pages/WACIIssue.vue
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/test/fixtures/.env
  go.mod
  go.sum
  scripts/check_unit.sh
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
Labels: cla-signed
