Repository trustbloc/wallet, pull requests merged in 2022-06, with the labels that each got.

#1689 fix: Handle parent path of OIDC flow
  cmd/wallet-web/src/router/routes.js
Labels: cla-signed

#1690 chore: update to latest aries
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/test/fixtures/.env
  go.mod
  go.sum
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-web.yml
  test/mock/adapter/adapter.go
  test/mock/adapter/didcomm.go
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
Labels: cla-signed

#1691 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1692 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/test/fixtures/.env
  test/fixtures/wallet-web/.env
Labels: cla-signed

#1693 chore: updated uuid imports and other legacy deps
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/components/CredentialDetails/CredentialDetailsBannerComponent.vue
  cmd/wallet-web/src/components/CredentialDetails/RenameCredentialModalComponent.vue
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreviewComponent.vue
  cmd/wallet-web/src/components/Flyout/FlyoutComponent.vue
  cmd/wallet-web/src/components/Flyout/FlyoutMenuComponent.vue
  cmd/wallet-web/src/components/Header/HeaderComponent.vue
  cmd/wallet-web/src/components/Modal/ModalComponent.vue
  cmd/wallet-web/src/components/Navbar/NavbarComponent.vue
  cmd/wallet-web/src/components/Navbar/NavbarLinkComponent.vue
  cmd/wallet-web/src/components/Signout/SignoutComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/VaultCardComponent.vue
  cmd/wallet-web/src/components/TabbedInterface/TabsComponent.vue
  cmd/wallet-web/src/components/ToolTip/ToolTipComponent.vue
  cmd/wallet-web/src/components/Vaults/AddVaultModalComponent.vue
  cmd/wallet-web/src/components/Vaults/RenameVaultModalComponent.vue
  cmd/wallet-web/src/components/Vaults/VaultCardComponent.vue
  cmd/wallet-web/src/components/Vaults/VaultWelcomeBannerComponent.vue
  cmd/wallet-web/src/components/WACI/CredentialBannerComponent.vue
  cmd/wallet-web/src/components/WACI/CredentialDetailsTableComponent.vue
  cmd/wallet-web/src/components/WACI/CredentialOverviewComponent.vue
  cmd/wallet-web/src/components/WACI/WACIActionButtonsContainerComponent.vue
  cmd/wallet-web/src/layouts/DashboardLayout.vue
  cmd/wallet-web/src/layouts/GetLayout.vue
  cmd/wallet-web/src/layouts/OIDCInitiateLayout.vue
  cmd/wallet-web/src/layouts/OIDCLayout.vue
  cmd/wallet-web/src/layouts/OIDCSaveLayout.vue
  cmd/wallet-web/src/layouts/OIDCShareLayout.vue
  cmd/wallet-web/src/layouts/WACILayout.vue
  cmd/wallet-web/src/layouts/WACIShareLayout.vue
  cmd/wallet-web/src/mixins/common/helper.js
  cmd/wallet-web/src/mixins/get/getCredentialsByQuery.js
  cmd/wallet-web/src/pages/BlockNoAuthPage.vue
  cmd/wallet-web/src/pages/CHAPISharePage.vue
  cmd/wallet-web/src/pages/CredentialDetailsPage.vue
  cmd/wallet-web/src/pages/CredentialsPage.vue
  cmd/wallet-web/src/pages/MultipleQueryPage.vue
  cmd/wallet-web/src/pages/NotFoundPage.vue
  cmd/wallet-web/src/pages/OIDCSavePage.vue
  cmd/wallet-web/src/pages/OIDCShareOverviewPage.vue
  cmd/wallet-web/src/pages/OIDCSharePage.vue
  cmd/wallet-web/src/pages/SigninPage.vue
  cmd/wallet-web/src/pages/SignupPage.vue
  cmd/wallet-web/src/pages/StorePage.vue
  cmd/wallet-web/src/pages/VaultsPage.vue
  cmd/wallet-web/src/pages/WACIIssuePage.vue
  cmd/wallet-web/src/pages/WACIShareOverviewPage.vue
  cmd/wallet-web/src/pages/WACISharePage.vue
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/test/common.js
  cmd/wallet-web/test/specs/get.spec.js
  package-lock.json
  test/ui-automation/package-lock.json
  test/ui-automation/package.json
  test/ui-automation/test/specs/vault-interaction-flow.js
Labels: cla-signed

#1694 chore: removed unused deps
  test/ui-automation/package-lock.json
  test/ui-automation/package.json
Labels: cla-signed, type: chore, dependencies

#1697 fix: added missing import
  cmd/wallet-web/src/layouts/OIDCInitiateLayout.vue
  cmd/wallet-web/src/layouts/OIDCLayout.vue
  cmd/wallet-web/src/pages/CHAPISharePage.vue
Labels: cla-signed, type: fix, area: UI

#1704 fix: fixed issues in CHAPI share page
  cmd/wallet-web/src/layouts/GetLayout.vue
  cmd/wallet-web/src/mixins/get/getCredentialsByQuery.js
  cmd/wallet-web/src/pages/CHAPISharePage.vue
Labels: cla-signed, type: fix, area: UI

#1698 feat: Update EDV and agent-sdk versions
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  go.mod
  go.sum
  test/fixtures/wallet-web/.env
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
Labels: cla-signed

#1713 chore: update kms
  scripts/generate_test_keys.sh
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
Labels: cla-signed

#1712 chore: updated gjson to 1.14.1
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  go.mod
  go.sum
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
  test/mock/demo-login-consent-server/go.mod
  test/mock/demo-login-consent-server/go.sum
Labels: cla-signed, type: chore, dependencies

#1711 feat: Initiate Gnap flow for wallet integration
  cmd/wallet-web/src/mixins/gnap/gnap.js
  cmd/wallet-web/src/mixins/index.js
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed

#1715 fix: vault filter flyout button text to be reactive
  cmd/wallet-web/src/pages/CredentialsPage.vue
  cmd/wallet-web/src/translations/CredentialDetails/fr.json
Labels: type: bug, cla-signed, area: UI

#1723 chore: update latest afgo commit
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  go.mod
  go.sum
  test/fixtures/wallet-web/.env
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
Labels: cla-signed

#1727 fix: updated automation test script
  test/ui-automation/test/helpers/chapi.js
Labels: cla-signed, type: fix, area: integration tests

#1724 feat: Prepare valid gnap request to access agent sdk request access method
  cmd/wallet-web/src/config/gnap-access-token.json
  cmd/wallet-web/src/mixins/gnap/gnap.js
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/modules/options.js
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/static/config/gnap-access-token.json
Labels: cla-signed

#1728 fix: added skeleton loader for credential details page to fix screen alignment issue
  cmd/wallet-web/src/components/SkeletonLoader/CredentialDetailsBannerSkeletonComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoaderComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/VerifiedInformationSkeletonComponent.vue
  cmd/wallet-web/src/layouts/DashboardLayout.vue
  cmd/wallet-web/src/pages/CredentialDetailsPage.vue
Labels: cla-signed, type: fix, area: UI

#1730 fix: CHAPI Multiple Credential Share failure
  cmd/wallet-web/src/mixins/common/helper.js
Labels: cla-signed, area: UI

#1731 feat: Create gnap key pair once per session
  cmd/wallet-web/src/mixins/gnap/gnap.js
  cmd/wallet-web/src/mixins/gnap/store.js
  cmd/wallet-web/src/mixins/index.js
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed

#1733 chore: update afgo version.
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  go.mod
  go.sum
Labels: cla-signed

#1734 refactor: remove getCredentialManifestData
  cmd/wallet-web/src/config/credentialDisplayData.js
  cmd/wallet-web/src/pages/CredentialsPage.vue
  cmd/wallet-web/src/pages/MultipleQueryPage.vue
  cmd/wallet-web/src/pages/OIDCSavePage.vue
  cmd/wallet-web/src/pages/OIDCSharePage.vue
  cmd/wallet-web/src/pages/WACIIssuePage.vue
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/test/common.js
  test/fixtures/wallet-web/static/config/credentialDisplayData.json
Labels: type: enhancement, cla-signed, area: UI

#1739 chore: update agent sdk.
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1742 feat: Implement GNAP Continue flow
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/config/gnap-access-token.json
  cmd/wallet-web/src/mixins/gnap/gnap.js
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/src/store/modules/user.js
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
  test/fixtures/wallet-web/docker-compose-web.yml
  test/fixtures/wallet-web/static/config/access_policy.json
  test/fixtures/wallet-web/static/config/gnap-access-token.json
Labels: cla-signed

#1749 feat: added gnap access token and subjectId to agent opts
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/modules/user.js
  test/fixtures/wallet-web/.env
Labels: type: enhancement, cla-signed, area: UI

#1736 chore: added check for null before adding to localStorage
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed, area: UI

#1745 feat: Added skeleton loaders to Credentials Page
  cmd/wallet-web/src/components/SkeletonLoader/CredentialDetailsBannerSkeletonComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/CredentialPreviewSkeletonComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoaderComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/VaultCardComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/VaultCardSkeletonComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/VerifiedInformationSkeletonComponent.vue
  cmd/wallet-web/src/pages/CredentialsPage.vue
  cmd/wallet-web/src/pages/VaultsPage.vue
Labels: type: enhancement, cla-signed, area: UI

#1752 fix: fixed navigation guard issue
  cmd/wallet-web/src/components/SkeletonLoader/CredentialPreviewSkeletonComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoaderComponent.vue
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed, type: fix, area: UI

#1760 refactor: VaultsPage to use setup script
  cmd/wallet-web/src/pages/VaultsPage.vue
Labels: cla-signed, type: refactor, area: UI
