Repository trustbloc/wallet, pull requests merged in 2022-02, with the labels that each got.

#1470 feat: implemented UI for sharing multiple credentials in WACI
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
  cmd/wallet-web/src/components/Header/Header.vue
  cmd/wallet-web/src/components/WACI/CredentialBanner.vue
  cmd/wallet-web/src/components/WACI/CredentialDetailsTable.vue
  cmd/wallet-web/src/components/WACI/CredentialOverview.vue
  cmd/wallet-web/src/layouts/WACI.vue
  cmd/wallet-web/src/layouts/WACIShareLayout.vue
  cmd/wallet-web/src/pages/WACIIssue.vue
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/src/pages/WACIShareOverview.vue
  cmd/wallet-web/src/router/routes.js
  cmd/wallet-web/src/translations/CHAPI/en.json
  cmd/wallet-web/src/translations/CHAPI/fr.json
  cmd/wallet-web/src/translations/WACI/en.json
  cmd/wallet-web/src/translations/WACI/fr.json
Labels: type: enhancement, cla-signed, area: UI

#1479 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/config/credential-output-descriptors.json
  cmd/wallet-web/src/mixins/common/helper.js
  cmd/wallet-web/src/mixins/get/didConn.js
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/test/fixtures/testdata/credential-output-descriptors.json
  test/mock/adapter/adapter.go
Labels: cla-signed

#1484 fix: update CHAPI wallet name to wallet url
  scripts/run_ui_automation.sh
  test/ui-automation/wdio.conf.js
Labels: cla-signed

#1485 test: disable vault-test to unblock build failure
  test/ui-automation/wdio.shared.conf.js
Labels: cla-signed

#1488 test: add component healthchecks before running tests
  scripts/run_ui_automation.sh
Labels: cla-signed

#1480 feat: optimized automation tests
  cmd/wallet-web/src/components/Modal/Modal.vue
  cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
  cmd/wallet-web/src/components/Vaults/VaultCard.vue
  cmd/wallet-web/src/pages/Signup.vue
  cmd/wallet-web/src/pages/Vaults.vue
  images/wallet-web/templates/default.conf.template
  scripts/run_ui_automation.sh
  test/ui-automation/package-lock.json
  test/ui-automation/package.json
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/credential-interaction-flow.js
  test/ui-automation/test/specs/vault-interaction-flow.js
  test/ui-automation/test/specs/waci-issuance-flow.js
  test/ui-automation/test/specs/waci-share-flow.js
  test/ui-automation/wdio.shared.conf.js
Labels: type: enhancement, cla-signed, area: integration tests

#1492 chore: incresed waitFor timeout in automation tests
  test/ui-automation/wdio.shared.conf.js
Labels: cla-signed, type: chore, area: integration tests

#1489 feat: didcomm v2 support for WACI
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/mixins/common/register.js
  cmd/wallet-web/src/store/modules/options.js
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  scripts/run_ui_automation.sh
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-demo.yml
  test/fixtures/wallet-web/docker-compose-web.yml
  test/mock/adapter/adapter.go
  test/mock/adapter/didcomm.go
  test/mock/adapter/main.go
  test/mock/adapter/templates/issuer.html
  test/mock/adapter/templates/verifier.html
  test/ui-automation/test/specs/waci-issuance-flow.js
  test/ui-automation/test/specs/waci-share-flow.js
Labels: cla-signed

#1494 fix: enable webkms for wallet
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/fixtures/wallet-web/docker-compose-web.yml
Labels: cla-signed

#1497 chore: manifests for demo VCs
  cmd/wallet-web/src/config/credential-output-descriptors.json
Labels: cla-signed

#1498 feat: added automation tests for rename a vault flow
  cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
  cmd/wallet-web/src/components/Vaults/RenameVaultModal.vue
  cmd/wallet-web/src/pages/Vaults.vue
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/vault-interaction-flow.js
Labels: type: enhancement, cla-signed, area: integration tests

#1501 test: added automation test for removing vaults
  cmd/wallet-web/src/components/Modal/Modal.vue
  cmd/wallet-web/src/pages/Vaults.vue
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/vault-interaction-flow.js
  test/ui-automation/wdio.shared.conf.js
Labels: cla-signed, type: test, area: integration tests

#1502 test: validate welcome banner dismissal
  cmd/wallet-web/src/components/Signout/Signout.vue
  cmd/wallet-web/src/layouts/DashboardLayout.vue
  cmd/wallet-web/src/pages/Vaults.vue
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/credential-interaction-flow.js
  test/ui-automation/test/specs/vault-interaction-flow.js
  test/ui-automation/test/specs/waci-issuance-flow.js
  test/ui-automation/test/specs/waci-share-flow.js
Labels: cla-signed, type: test, area: integration tests

#1507 feat: updated vaults screen to use metadata endpoints
  cmd/wallet-web/src/pages/Vaults.vue
Labels: type: enhancement, cla-signed, area: UI

#1508 chore: PRC flow in wallet WACI automation tests
  test/mock/adapter/adapter.go
  test/mock/adapter/sampledata/credential_manifest.json
  test/mock/adapter/sampledata/fulfillment_dl_vp.json
  test/mock/adapter/sampledata/sample_prc_fulfillment.json
  test/mock/adapter/sampledata/sample_prc_fulfillment_unsigned.json
  test/mock/adapter/sampledata/sample_udc_fulfillment.json
  test/ui-automation/test/specs/waci-flow.js
Labels: cla-signed

#1519 chore: update to latest hub-router and agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/options.js
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-web.yml
  test/mock/adapter/didcomm.go
  test/ui-automation/test/specs/waci-flow.js
Labels: cla-signed

#1523 fix: media profile default value
  cmd/wallet-web/src/store/modules/options.js
  test/mock/adapter/didcomm.go
Labels: cla-signed

#1525 fix: blindedrouter flag
  cmd/wallet-web/src/mixins/get/didConn.js
  cmd/wallet-web/src/mixins/get/getCredentialsByQuery.js
Labels: cla-signed

#1526 feat: websocket read limit support
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-server/startcmd/agentconfig.go
  cmd/wallet-server/startcmd/start_test.go
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/options.js
  go.mod
  go.sum
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  test/fixtures/wallet-web/docker-compose-web.yml
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
  test/mock/adapter/sampledata/sample_prc_fulfillment.json
  test/mock/adapter/sampledata/sample_prc_fulfillment_unsigned.json
Labels: cla-signed
