Repository trustbloc/wallet, pull requests merged in 2022-03, with the labels that each got.

#1534 chore: default manifests - fixing prc image schema
  cmd/wallet-web/src/config/credential-output-descriptors.json
Labels: cla-signed

#1538 test: remove unused docker containers
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
  test/fixtures/wallet-web/docker-compose-web.yml
Labels: cla-signed, area: integration tests

#1540 test: trustbloc docker dep update
  test/fixtures/wallet-web/.env
Labels: cla-signed

#1543 chore: trustbloc auth and router docker version update
  test/fixtures/wallet-web/.env
  test/ui-automation/wdio.shared.conf.js
Labels: cla-signed

#1544 chore: increase healthcheck sleep time
  scripts/run_ui_automation.sh
Labels: cla-signed

#1537 feat: upgraded to tailwindcss v3, added support for DWC
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/components/CredentialDetails/Banner.vue
  cmd/wallet-web/src/components/CredentialDetails/DeleteCredentialModal.vue
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
  cmd/wallet-web/src/components/Navbar/Navbar.vue
  cmd/wallet-web/src/components/WACI/CredentialBanner.vue
  cmd/wallet-web/src/components/WACI/CredentialOverview.vue
  cmd/wallet-web/src/config/credential-output-descriptors.json
  cmd/wallet-web/src/config/credentialDisplayData.js
  cmd/wallet-web/src/layouts/DashboardLayout.vue
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/pages/DIDAuth.vue
  cmd/wallet-web/src/pages/DIDConnect.vue
  cmd/wallet-web/src/pages/MultipleQuery.vue
  cmd/wallet-web/src/pages/PresentationDefQuery.vue
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/tailwind.js
  cmd/wallet-web/test/fixtures/testdata/credential-output-descriptors.json
  test/fixtures/wallet-web/static/config/credentialDisplayData.json
  test/mock/adapter/sampledata/credential_manifest.json
  test/mock/adapter/templates/css/tailwind.css
  test/mock/demo-login-consent-server/templates/css/tailwind.css
  test/ui-automation/test/specs/credential-interaction-flow.js
  test/ui-automation/test/specs/waci-flow.js
Labels: type: enhancement, cla-signed, area: UI

#1545 test: update mock issuer/verifier to support different type of flows
  test/mock/adapter/adapter.go
  test/mock/adapter/templates/issuer/issuer.html
  test/mock/adapter/templates/issuer/waci-issuer.html
  test/mock/adapter/templates/verifier/oidc-verifier.html
  test/mock/adapter/templates/verifier/verifier.html
  test/mock/adapter/templates/verifier/waci-verifier.html
  test/ui-automation/test/specs/credential-interaction-flow.js
  test/ui-automation/test/specs/waci-flow.js
  test/ui-automation/wdio.conf.js
Labels: cla-signed

#1549 test: [waci-share] Support to dynamically add Presentation Exchange (PEx)
  test/mock/adapter/adapter.go
  test/mock/adapter/templates/verifier/waci-verifier.html
  test/ui-automation/wdio.conf.js
Labels: cla-signed

#1551 test: [waci-issuance] Support to dynamically add Credential Manifest (CM)
  test/fixtures/wallet-web/docker-compose-demo.yml
  test/fixtures/wallet-web/docker-compose-web.yml
  test/mock/adapter/adapter.go
  test/mock/adapter/sampledata/credential_manifest.json
  test/mock/adapter/templates/issuer/waci-issuer.html
  test/ui-automation/test/specs/waci-flow.js
Labels: cla-signed

#1552 test: oidc4vp demo setup
  test/fixtures/wallet-web/docker-compose-demo.yml
  test/mock/adapter/adapter.go
  test/mock/adapter/templates/verifier/oidc-verifier.html
  test/ui-automation/test/specs/waci-flow.js
Labels: cla-signed

#1554 test: oidc-share - pass pres_def and handle callback
  test/mock/adapter/adapter.go
  test/mock/adapter/common.go
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
  test/mock/adapter/templates/verifier/oidc-verifier.html
Labels: cla-signed

#1553 chore: OIDC share (Route, read claims and VCS Search)
  cmd/wallet-web/src/layouts/OIDC.vue
  cmd/wallet-web/src/layouts/OIDCShareLayout.vue
  cmd/wallet-web/src/pages/OIDCShare.vue
  cmd/wallet-web/src/pages/OIDCShareOverview.vue
  cmd/wallet-web/src/router/routes.js
Labels: cla-signed

#1574 chore: remove device flow code (unused)
  cmd/wallet-server/startcmd/start.go
  cmd/wallet-server/startcmd/start_test.go
  pkg/restapi/device/appleattestation.go
  pkg/restapi/device/deviceapi.go
  pkg/restapi/device/operations.go
  pkg/restapi/device/operations_test.go
  test/fixtures/wallet-web/couchdb-config/config.ini
  test/mock/authenticator/authenticator.go
  test/mock/authenticator/authenticator_test.go
Labels: cla-signed

#1576 test: [waci] validate saved credential
  test/ui-automation/test/specs/waci-flow.js
Labels: cla-signed

#1575 chore: update import path from edge-agent to wallet
  .golangci.yml
  Makefile
  README.md
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-server/main.go
  cmd/wallet-server/startcmd/start.go
  cmd/wallet-server/startcmd/start_test.go
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/src/components/Modal/Modal.vue
  go.mod
  go.sum
  images/wallet-server/Dockerfile
  pkg/restapi/common/common_test.go
  pkg/restapi/common/httphandler_test.go
  pkg/restapi/common/oidc/mock_test.go
  pkg/restapi/common/store/tokens/store.go
  pkg/restapi/common/store/user/store.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  pkg/restapi/oidc/signer.go
  pkg/restapi/wallet/controller.go
  pkg/restapi/wallet/controller_test.go
  scripts/check_unit.sh
  scripts/generate_test_keys.sh
  test/mock/adapter/go.mod
  test/mock/adapter/image/Dockerfile
  test/mock/demo-login-consent-server/go.mod
  test/mock/demo-login-consent-server/image/Dockerfile
Labels: cla-signed

#1584 fix: Icons are not loading in credential list page
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
Labels: cla-signed

#1570 chore: Populating details in OIDC Share and passing "state" and token params
  cmd/wallet-web/src/components/WACI/CredentialDetailsTable.vue
  cmd/wallet-web/src/layouts/OIDC.vue
  cmd/wallet-web/src/pages/OIDCShare.vue
  cmd/wallet-web/src/router/routes.js
  test/mock/adapter/adapter.go
  test/mock/adapter/templates/verifier/oidc-verifier.html
Labels: cla-signed

#1593 chore: Removing share success page OIDC
  cmd/wallet-web/src/pages/OIDCShare.vue
Labels: cla-signed

#1592 test: [oidc4vp] display success/error message, id_token and vp_token
  test/mock/adapter/adapter.go
  test/mock/adapter/templates/verifier/oidc-verifier.html
Labels: cla-signed

#1569 feat: added support for DWC in WACI Issue, Store and updated credentials screen
  cmd/wallet-web/src/components/CredentialDetails/Banner.vue
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
  cmd/wallet-web/src/components/WACI/CredentialBanner.vue
  cmd/wallet-web/src/components/WACI/CredentialDetailsTable.vue
  cmd/wallet-web/src/components/WACI/CredentialOverview.vue
  cmd/wallet-web/src/pages/WACIIssue.vue
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/src/translations/WACI/en.json
Labels: type: enhancement, cla-signed, area: UI

#1603 chore: add dynamic wallet credential manifest
  test/fixtures/wallet-web/static/config/credential-output-descriptors.json
Labels: cla-signed

#1595 feat: Implement rename credential change
  cmd/wallet-web/src/components/CredentialDetails/DeleteCredentialModal.vue
  cmd/wallet-web/src/components/CredentialDetails/RenameCredentialModal.vue
  cmd/wallet-web/src/components/InputField/InputField.vue
  cmd/wallet-web/src/components/Modal/Modal.vue
  cmd/wallet-web/src/components/WACI/CredentialOverview.vue
  cmd/wallet-web/src/pages/CredentialDetails.vue
  cmd/wallet-web/src/pages/Credentials.vue
  cmd/wallet-web/src/pages/Vaults.vue
  cmd/wallet-web/src/pages/WACIIssue.vue
  cmd/wallet-web/src/pages/WACIShare.vue
  cmd/wallet-web/src/translations/CredentialDetails/en.json
  cmd/wallet-web/src/translations/CredentialDetails/fr.json
Labels: cla-signed

#1611 fix: WACI share shows missing credential page before sharing credential
  cmd/wallet-web/src/pages/OIDCShare.vue
  cmd/wallet-web/src/pages/WACIShare.vue
Labels: cla-signed

#1598 feat: updated CHAPI Store to support DWC
  cmd/wallet-web/karma.conf.js
  cmd/wallet-web/src/pages/Store.vue
  cmd/wallet-web/test/fixtures/testdata/credential-output-descriptors.json
Labels: type: enhancement, cla-signed, area: UI

#1618 fix: fixed issue with certain button styles not applying
  cmd/wallet-web/src/components/CredentialDetails/DeleteCredentialModal.vue
  cmd/wallet-web/src/components/CredentialDetails/RenameCredentialModal.vue
  cmd/wallet-web/src/components/DIDManagement/Preferences.vue
  cmd/wallet-web/src/components/Modal/Modal.vue
  cmd/wallet-web/src/components/StyledButton/StyledButton.vue
  cmd/wallet-web/src/components/Vaults/AddVaultModal.vue
  cmd/wallet-web/src/components/Vaults/DeleteVaultModal.vue
  cmd/wallet-web/src/components/Vaults/RenameVaultModal.vue
  cmd/wallet-web/src/components/WACI/WACICredentialsMissing.vue
  cmd/wallet-web/src/components/WACI/WACIError.vue
  cmd/wallet-web/src/components/WACI/WACISuccess.vue
  cmd/wallet-web/src/pages/BlockNoAuth.vue
  cmd/wallet-web/src/pages/OIDCShare.vue
  cmd/wallet-web/src/pages/WACIIssue.vue
  cmd/wallet-web/src/pages/WACIShare.vue
Labels: cla-signed, type: fix, area: UI

#1617 feat: enabled vault name in WACI/OIDC share flows
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/OIDCShare.vue
  cmd/wallet-web/src/pages/WACIIssue.vue
  cmd/wallet-web/src/pages/WACIShare.vue
Labels: type: enhancement, cla-signed, area: UI

#1621 chore: upgraded to latest aries-framework-go and edge-core
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/test/fixtures/.env
  go.mod
  go.sum
  pkg/restapi/oidc/webkms.go
  pkg/restapi/oidc/webkms_test.go
  test/fixtures/wallet-web/.env
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
Labels: cla-signed, type: chore, dependencies

#1623 fix: Background of the icon was missing
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreview.vue
Labels: cla-signed

#1626 chore: update to release dependencies
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/pages/OIDCShare.vue
  cmd/wallet-web/test/fixtures/.env
  go.mod
  go.sum
  test/fixtures/wallet-web/.env
Labels: cla-signed

#1620 chore: VP Token generation OIDC Share
  cmd/wallet-web/src/pages/OIDCShare.vue
  test/mock/adapter/adapter.go
  test/mock/adapter/common.go
Labels: cla-signed
