Repository trustbloc/wallet, pull requests merged in 2022-07, with the labels that each got.

#1779 chore: edv image update
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
Labels: cla-signed

#1780 chore: agent-sdk update
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1782 fix: ran linter
  cmd/wallet-web/src/components/CredentialDetails/CredentialDetailsBannerComponent.vue
  cmd/wallet-web/src/components/CredentialDetails/DeleteCredentialModalComponent.vue
  cmd/wallet-web/src/components/CredentialDetails/RenameCredentialModalComponent.vue
  cmd/wallet-web/src/components/CredentialPreview/CredentialPreviewComponent.vue
  cmd/wallet-web/src/components/CustomSelect/CustomSelectComponent.vue
  cmd/wallet-web/src/components/DIDManagement/CreateOrbComponent.vue
  cmd/wallet-web/src/components/DIDManagement/DIDPreferencesComponent.vue
  cmd/wallet-web/src/components/DIDManagement/ImportDIDComponent.vue
  cmd/wallet-web/src/components/Footer/FooterComponent.vue
  cmd/wallet-web/src/components/Modal/ModalComponent.vue
  cmd/wallet-web/src/components/Navbar/NavbarComponent.vue
  cmd/wallet-web/src/components/Navbar/NavbarLinkComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/CredentialDetailsBannerSkeletonComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/CredentialPreviewSkeletonComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/SkeletonLoaderComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/VaultCardSkeletonComponent.vue
  cmd/wallet-web/src/components/SkeletonLoader/VerifiedInformationSkeletonComponent.vue
  cmd/wallet-web/src/components/StyledButton/StyledButtonComponent.vue
  cmd/wallet-web/src/components/TabbedInterface/TabsComponent.vue
  cmd/wallet-web/src/components/ToastNotification/ToastNotificationComponent.vue
  cmd/wallet-web/src/components/ToolTip/ToolTipComponent.vue
  cmd/wallet-web/src/components/Vaults/AddVaultModalComponent.vue
  cmd/wallet-web/src/components/Vaults/DeleteVaultModalComponent.vue
  cmd/wallet-web/src/components/Vaults/RenameVaultModalComponent.vue
  cmd/wallet-web/src/components/Vaults/VaultCardComponent.vue
  cmd/wallet-web/src/components/Vaults/VaultWelcomeBannerComponent.vue
  cmd/wallet-web/src/components/WACI/CredentialBannerComponent.vue
  cmd/wallet-web/src/components/WACI/WACIActionButtonsContainerComponent.vue
  cmd/wallet-web/src/components/WACI/WACICredentialsMissingComponent.vue
  cmd/wallet-web/src/components/WACI/WACIErrorComponent.vue
  cmd/wallet-web/src/components/WACI/WACILoadingComponent.vue
  cmd/wallet-web/src/components/WACI/WACISharingComponent.vue
  cmd/wallet-web/src/components/WACI/WACISuccessComponent.vue
  cmd/wallet-web/src/layouts/DashboardLayout.vue
  cmd/wallet-web/src/layouts/OIDCLayout.vue
  cmd/wallet-web/src/layouts/OIDCSaveLayout.vue
  cmd/wallet-web/src/layouts/OIDCShareLayout.vue
  cmd/wallet-web/src/layouts/WACILayout.vue
  cmd/wallet-web/src/layouts/WACIShareLayout.vue
  cmd/wallet-web/src/pages/BlockNoAuthPage.vue
  cmd/wallet-web/src/pages/CHAPISharePage.vue
  cmd/wallet-web/src/pages/CredentialDetailsPage.vue
  cmd/wallet-web/src/pages/CredentialsPage.vue
  cmd/wallet-web/src/pages/MultipleQueryPage.vue
  cmd/wallet-web/src/pages/NotFoundPage.vue
  cmd/wallet-web/src/pages/OIDCSavePage.vue
  cmd/wallet-web/src/pages/OIDCShareOverviewPage.vue
  cmd/wallet-web/src/pages/OIDCSharePage.vue
  cmd/wallet-web/src/pages/ProviderPopupPage.vue
  cmd/wallet-web/src/pages/SigninPage.vue
  cmd/wallet-web/src/pages/SignupPage.vue
  cmd/wallet-web/src/pages/StorePage.vue
  cmd/wallet-web/src/pages/VaultsPage.vue
  cmd/wallet-web/src/pages/WACIIssuePage.vue
  cmd/wallet-web/src/pages/WACIShareOverviewPage.vue
  cmd/wallet-web/src/pages/WACISharePage.vue
Labels: cla-signed

#1785 feat: GNAP integration
  .github/workflows/build.yml
  cmd/wallet-web/src/App.vue
  cmd/wallet-web/src/components/Signout/SignoutComponent.vue
  cmd/wallet-web/src/mixins/gnap/gnap.js
  cmd/wallet-web/src/pages/VaultsPage.vue
  cmd/wallet-web/src/router/TheRoot.vue
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/router/routes.js
  cmd/wallet-web/src/store/index.js
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/src/store/modules/user.js
  docs/build.md
  scripts/generate_test_keys.sh
  test/fixtures/edv-oathkeeper/config.yaml
  test/fixtures/edv-oathkeeper/rules/resource-server.json
  test/fixtures/wallet-web/docker-compose-server.yml
  test/fixtures/wallet-web/docker-compose-web.yml
  test/fixtures/wallet-web/oathkeeper-config/auth-keyserver/config.yaml
  test/fixtures/wallet-web/oathkeeper-config/auth-keyserver/rules/resource-server.json
  test/fixtures/wallet-web/oathkeeper-config/ops-keyserver/config.yaml
  test/fixtures/wallet-web/oathkeeper-config/ops-keyserver/rules/resource-server.json
  test/ui-automation/test/helpers/wallet.js
Labels: type: enhancement, cla-signed, area: backend, area: UI, area: integration tests, area: docker

#1786 fix: Update provider file to use only gnap provider
  test/fixtures/wallet-web/hydra-config/demo_hydra_configure.sh
  test/fixtures/wallet-web/oidc-config/demo_providers.yaml
  test/ui-automation/test/helpers/wallet.js
Labels: cla-signed

#1790 fix: addressing comments for gnap integration and cleanup
  cmd/wallet-web/src/mixins/gnap/gnap.js
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/src/store/modules/user.js
Labels: cla-signed, type: fix, area: UI

#1793 fix: Update wallet with latest agent-sdk change
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/mixins/gnap/store.js
Labels: cla-signed

#1804 chore: update to latest auth
  test/fixtures/wallet-web/.env
Labels: cla-signed, type: chore, dependencies

#1807 chore: auth image update
  test/fixtures/wallet-web/.env
Labels: cla-signed

#1808 feat: integrated wallet-sdk http signature logic
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/mixins/gnap/gnap.js
  cmd/wallet-web/src/mixins/gnap/store.js
  cmd/wallet-web/src/router/index.js
Labels: type: enhancement, cla-signed, area: UI

#1812 fix: Added spinner as loading state for user authentication
  cmd/wallet-web/src/App.vue
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/modules/user.js
Labels: type: enhancement, cla-signed, area: UI

#1801 feat: validate gnap signatures on wasm calls to kms
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/store/modules/user.js
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
Labels: cla-signed

#1819 chore: updated to latest auth
  test/fixtures/wallet-web/.env
Labels: cla-signed, type: chore, dependencies

#1820 chore: updated to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed, type: chore, dependencies

#1818 chore: removed wallet-server container, cleaned up GNAP helpers
  .github/workflows/build.yml
  cmd/wallet-web/src/mixins/gnap/gnap.js
  cmd/wallet-web/src/mixins/gnap/store.js
  cmd/wallet-web/src/pages/ProviderPopupPage.vue
  cmd/wallet-web/src/pages/SigninPage.vue
  cmd/wallet-web/src/pages/SignupPage.vue
  cmd/wallet-web/src/store/modules/user.js
  docs/build.md
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  scripts/generate_test_keys.sh
  scripts/run_ui_automation.sh
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
  test/fixtures/wallet-web/docker-compose-web.yml
Labels: cla-signed, type: chore, area: UI, area: docker

#1823 chore: enable httpsig for gnap auth and edv
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
Labels: cla-signed

#1826 refactor: remove wallet-server component
  .codecov.yaml
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .golangci.yml
  Makefile
  README.md
  cmd/wallet-server/go.mod
  cmd/wallet-server/go.sum
  cmd/wallet-server/main.go
  cmd/wallet-server/main_test.go
  cmd/wallet-server/startcmd/agentconfig.go
  cmd/wallet-server/startcmd/start.go
  cmd/wallet-server/startcmd/start_test.go
  doc.go
  docs/components/wallet_server.md
  go.mod
  go.sum
  images/wallet-server/Dockerfile
  pkg/restapi/common/common.go
  pkg/restapi/common/common_test.go
  pkg/restapi/common/httphandler.go
  pkg/restapi/common/httphandler_test.go
  pkg/restapi/common/logutil/util.go
  pkg/restapi/common/oidc/api.go
  pkg/restapi/common/oidc/client.go
  pkg/restapi/common/oidc/client_test.go
  pkg/restapi/common/oidc/mock.go
  pkg/restapi/common/oidc/mock_test.go
  pkg/restapi/common/store/cookie/api.go
  pkg/restapi/common/store/cookie/mock.go
  pkg/restapi/common/store/cookie/store.go
  pkg/restapi/common/store/helper.go
  pkg/restapi/common/store/tokens/store.go
  pkg/restapi/common/store/user/store.go
  pkg/restapi/internal/mocks/mock_webhook.go
  pkg/restapi/internal/mocks/protocol/outofband.go
  pkg/restapi/internal/mocks/protocol/provider.go
  pkg/restapi/oidc/models.go
  pkg/restapi/oidc/operations.go
  pkg/restapi/oidc/operations_test.go
  pkg/restapi/oidc/signer.go
  pkg/restapi/oidc/webkms.go
  pkg/restapi/oidc/webkms_test.go
  pkg/restapi/wallet/controller.go
  pkg/restapi/wallet/controller_test.go
  pkg/restapi/wallet/operation/operations.go
  pkg/restapi/wallet/operation/operations_test.go
  scripts/check_lint.sh
  scripts/check_unit.sh
  test/fixtures/wallet-web/.env
Labels: cla-signed

#1828 chore: remove wallet-server openapi scripts
  Makefile
  scripts/generate-openapi-demo-specs.sh
  scripts/generate-openapi-spec.sh
  scripts/run-openapi-demo.sh
Labels: cla-signed

#1829 chore: update auth
  test/fixtures/wallet-web/.env
Labels: cla-signed
