Repository trustbloc/wallet, pull requests merged in 2022-08, with the labels that each got.

#1840 fix: use title from credentialmanifest
  cmd/wallet-web/src/pages/CredentialDetailsPage.vue
  cmd/wallet-web/src/pages/CredentialsPage.vue
  cmd/wallet-web/src/pages/OIDCSharePage.vue
  cmd/wallet-web/src/pages/WACISharePage.vue
Labels: cla-signed, type: fix, area: UI

#1848 feat: added check for empty optional properties for resolveManifest
  cmd/wallet-web/src/mixins/common/helper.js
  cmd/wallet-web/src/pages/CHAPISharePage.vue
  cmd/wallet-web/src/pages/MultipleQueryPage.vue
  cmd/wallet-web/src/pages/OIDCSavePage.vue
  cmd/wallet-web/src/pages/StorePage.vue
  cmd/wallet-web/src/pages/WACIIssuePage.vue
Labels: type: enhancement, cla-signed, area: UI

#1849 chore: update afgo version
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/components/WACI/CredentialDetailsTableComponent.vue
  cmd/wallet-web/src/config/credential-output-descriptors.json
  cmd/wallet-web/src/mixins/gnap/gnap.js
  cmd/wallet-web/src/pages/CHAPISharePage.vue
  cmd/wallet-web/src/pages/CredentialDetailsPage.vue
  cmd/wallet-web/src/pages/MultipleQueryPage.vue
  cmd/wallet-web/src/pages/StorePage.vue
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/src/store/modules/user.js
  cmd/wallet-web/test/common.js
  cmd/wallet-web/test/fixtures/.env
  cmd/wallet-web/test/fixtures/agent-config.json
  cmd/wallet-web/test/fixtures/testdata/credential-output-descriptors.json
  images/wallet-web/templates/default.conf.template
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/static/config/credential-output-descriptors.json
  test/mock/adapter/adapter.go
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
  test/mock/adapter/templates/issuer/oidc-issuer.html
  test/mock/adapter/templates/issuer/waci-issuer.html
  test/ui-automation/test/specs/oidc-flow.js
  test/ui-automation/test/specs/waci-flow.js
Labels: cla-signed

#1851 fix: register with mediator for didcomm v1, fixing WACI DIDComm V1 tests
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/mixins/common/register.js
  test/fixtures/wallet-web/.env
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
  test/ui-automation/test/specs/waci-flow.js
Labels: cla-signed

#1852 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/mock/adapter/adapter.go
  test/mock/adapter/go.mod
  test/mock/adapter/go.sum
Labels: cla-signed

#1855 fix: sandbox issue with credential manifests
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/src/config/credential-output-descriptors.json
  cmd/wallet-web/src/mixins/common/helper.js
  cmd/wallet-web/src/pages/CHAPISharePage.vue
  cmd/wallet-web/src/pages/MultipleQueryPage.vue
  cmd/wallet-web/src/pages/OIDCSavePage.vue
  cmd/wallet-web/src/pages/StorePage.vue
  cmd/wallet-web/src/pages/WACIIssuePage.vue
  cmd/wallet-web/test/fixtures/testdata/credential-output-descriptors.json
  test/fixtures/wallet-web/static/config/credential-output-descriptors.json
Labels: cla-signed

#1846 feat: added a flag to enable DIDComm
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/scripts/setup_assets.sh
  cmd/wallet-web/src/mixins/common/register.js
  cmd/wallet-web/src/pages/NotFoundPage.vue
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/router/routes.js
  cmd/wallet-web/src/store/modules/options.js
  cmd/wallet-web/src/store/modules/user.js
  cmd/wallet-web/test/fixtures/agent-config.json
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  test/fixtures/wallet-web/docker-compose-web.yml
Labels: type: enhancement, cla-signed, area: UI

#1856 chore: updated to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1857 fix: redirect user to correct page upon signin
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/store/modules/user.js
  test/ui-automation/test/helpers/wallet.js
Labels: cla-signed

#1860 test: added test case for missing default manifest in wallet + resolveManifest changes
  cmd/wallet-web/src/mixins/common/helper.js
  test/ui-automation/test/specs/credential-interaction-flow.js
Labels: cla-signed

#1862 feat: added flag to enable CHAPI in wallet
  cmd/wallet-web/.eslintrc.js
  cmd/wallet-web/src/App.vue
  cmd/wallet-web/src/components/Signout/SignoutComponent.vue
  cmd/wallet-web/src/layouts/GetLayout.vue
  cmd/wallet-web/src/main.js
  cmd/wallet-web/src/pages/StorePage.vue
  cmd/wallet-web/src/pages/WorkerPage.vue
  cmd/wallet-web/src/router/TheRoot.vue
  cmd/wallet-web/src/router/index.js
  cmd/wallet-web/src/router/routes.js
  cmd/wallet-web/src/store/modules/options.js
  images/wallet-web/Dockerfile
  images/wallet-web/templates/default.conf.template
  test/fixtures/wallet-web/docker-compose-web.yml
Labels: type: enhancement, cla-signed, area: UI

#1864 chore: upgraded vue-i18n
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  test/ui-automation/wdio.shared.conf.js
Labels: cla-signed, type: chore, dependencies

#1866 feat: pick mysql image based on architecture type
  scripts/wallet_web_start.sh
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
Labels: type: enhancement, cla-signed

#1870 refactor: remove manual check for arch since mysql supports both by default now
  scripts/wallet_web_start.sh
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
Labels: cla-signed

#1869 feat: Update agent-sdk, rename Cred Fulfillment to Cred Response
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/mixins/common/helper.js
  cmd/wallet-web/src/mixins/get/didConn.js
  cmd/wallet-web/src/pages/CHAPISharePage.vue
  cmd/wallet-web/src/pages/MultipleQueryPage.vue
  cmd/wallet-web/src/pages/StorePage.vue
  cmd/wallet-web/src/pages/WACIIssuePage.vue
  test/fixtures/wallet-web/static/contexts/ld-contexts.json
  test/mock/adapter/adapter.go
  test/mock/adapter/templates/issuer/waci-issuer.html
  test/ui-automation/wdio.shared.conf.js
Labels: cla-signed
