Repository trustbloc/wallet, pull requests merged in 2022-09, with the labels that each got.

#1871 test: updated configs to run both vc wallet and regular wallet instances
  .github/workflows/build.yml
  Makefile
  docs/build.md
  scripts/run_vcwallet_ui_automation.sh
  scripts/run_wallet_ui_automation.sh
  test/fixtures/wallet-web/docker-compose-web.yml
  test/ui-automation/package-lock.json
  test/ui-automation/package.json
  test/ui-automation/test/helpers/chapi.js
  test/ui-automation/test/helpers/wallet.js
  test/ui-automation/test/specs/credential-interaction-flow.js
  test/ui-automation/test/specs/oidc-flow.js
  test/ui-automation/test/specs/vault-interaction-flow.js
  test/ui-automation/test/specs/waci-flow.js
  test/ui-automation/wdio.conf.vcwallet.js
  test/ui-automation/wdio.conf.wallet.js
  test/ui-automation/wdio.shared.conf.js
Labels: type: enhancement, cla-signed, area: integration tests

#1872 test: [oidc-presentation-test] validate vc-type
  test/mock/adapter/adapter.go
  test/mock/adapter/templates/verifier/oidc-verifier.html
  test/ui-automation/test/specs/oidc-flow.js
Labels: cla-signed

#1880 chore: replace sidetree-mock with orb
  Makefile
  cmd/wallet-web/scripts/generate_test_keys.sh
  cmd/wallet-web/scripts/setup_test.sh
  cmd/wallet-web/test/fixtures/.env
  cmd/wallet-web/test/fixtures/agent-config.json
  cmd/wallet-web/test/fixtures/docker-compose.yml
  scripts/generate_wallet_web_test_keys.sh
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-demo.yml
  test/fixtures/wallet-web/docker-compose-web.yml
Labels: cla-signed

#1884 chore: update to latest agent-sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1888 fix: Docker warning when using frapsoft/openssl on arm64 system
  Makefile
Labels: cla-signed

#1893 chore: update to latest agent sdk
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
Labels: cla-signed

#1895 fix: updated publish requirements for main branch
  .github/workflows/build.yml
Labels: cla-signed, type: fix, area: CI/CD

#1883 feat: Add new demo page to handle issuance initiate request and qrcode scanner
  cmd/wallet-web/package-lock.json
  cmd/wallet-web/package.json
  cmd/wallet-web/src/assets/img/qr-code-scan-icon.svg
  cmd/wallet-web/src/pages/InitiateProtocolPage.vue
  cmd/wallet-web/src/router/routes.js
Labels: cla-signed

#1898 chore(deps): chore(deps): bump kms from v0.1.9-snapshot-9e7901f to v0.1.9-snapshot-1e53108
  test/fixtures/wallet-web/.env
  test/fixtures/wallet-web/docker-compose-server.yml
Labels: cla-signed
